Streaming gateway
kube-HPC/hkube pull request #1234
Opened 2021-04-20 16:09 UTC by NassiHarel

2021-04-22 07:33 UTC, NassiHarel reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1234)* status: 0 of 68 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/api/rest-api/internal/exec.js, line 15 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1234#-MYsTjP12ziA6NyqOUYk:-MYsTjP12ziA6NyqOUYl:b-or5vu0) ([raw file](https://github.com/kube-hpc/hkube/blob/808471eb1c9cec0712a928336e055791a7edefd5/core/api-server/api/rest-api/internal/exec.js#L15)):*
> ```
> gatewayURLs
> ```
Don't always return gatewayURLs


<!-- Sent from Reviewable.io -->

2021-04-22 07:41 UTC, NassiHarel commented on core/api-server/lib/service/execution.js
> +            await Promise.all(pipeline.nodes.map(async node => {
use filter instead of if

2021-04-22 07:41 UTC, NassiHarel commented on core/api-server/lib/service/execution.js
> +            await Promise.all(pipeline.nodes.map(async node => {
Move this to different function

2021-04-22 07:41 UTC, NassiHarel commented on core/api-server/lib/service/execution.js
> +            return { jobId, gatewayURLs };
dont return gatewayURLs

2021-04-22 07:41 UTC, NassiHarel commented on core/api-server/lib/service/gateway.js
> +    _hasCron(pipeline, gatewayName) {
remove this _hasCron

2021-04-22 07:41 UTC, NassiHarel commented on core/api-server/tests/exec-raw.js
> +        it('should insert gateway', async () => {
you should add tests for 
- gateway without a name
- gateway not exists
- gateway already exists

2021-04-25 07:46 UTC, NassiHarel commented on core/api-server/lib/service/execution.js
> +                }
gateways.push({ [node.nodeName]: `gateway/${name}` });

2021-04-25 07:56 UTC, NassiHarel commented on core/api-server/lib/service/gateway.js
> +        await this._stopAllCrons(gatewayName);
remove not used code

2021-04-26 05:52 UTC, golanha commented
/deploy

2021-04-26 07:51 UTC, golanha commented
/deploy

2021-04-26 09:04 UTC, golanha commented
/deploy

2021-04-26 09:40 UTC, NassiHarel commented
/deploy

2021-04-26 10:57 UTC, NassiHarel commented
/deploy

2021-04-26 12:23 UTC, NassiHarel commented
/deploy

2021-04-26 12:59 UTC, NassiHarel commented
/deploy

2021-04-26 13:28 UTC, NassiHarel commented
/deploy

2021-04-26 13:45 UTC, NassiHarel commented
/deploy

2021-04-27 11:50 UTC, NassiHarel commented
/deploy

2021-04-27 11:57 UTC, NassiHarel commented
/deploy

2021-04-28 12:33 UTC, NassiHarel commented
/deploy

2021-04-28 12:55 UTC, NassiHarel commented
/deploy

2021-04-29 07:02 UTC, NassiHarel commented
/deploy

2021-04-29 11:04 UTC, NassiHarel commented
/deploy

2021-05-10 08:47 UTC, yehiyam reviewed
> Reviewed 1 of 37 files at r1, 1 of 81 files at r10.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1234)* status: 2 of 122 files reviewed, 7 unresolved discussions (waiting on @golanha)



<!-- Sent from Reviewable.io -->

2021-05-10 11:25 UTC, golanha submitted a review, later dismissed

2021-05-12 13:45 UTC, NassiHarel reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1234)* status: 109 of 140 files reviewed, 12 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-gateway/README.md, line 1 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KSwjN8klAZLLBbOhv:-M_VXmdR5e5IP1IV2oL1:b2nhswv) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/README.md#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I don't think this works anymore :-)
</blockquote></details>

Yep
___
*[core/algorithm-gateway/algorithm_unique_folder/index.js, line 1 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KT6HbCzsgUwA5cbp0:-M_VY8NQB-k524upRcWT:bmfwpm4) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/algorithm_unique_folder/index.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Why is this folder called algorithm_unique_folder? is it required by the wrapper?
</blockquote></details>

The `nodejs-wrapper` has a config like this:
```
config.algorithm = {
    path: process.env.ALGORITHM_PATH || 'algorithm_unique_folder',
    entryPoint: process.env.ALGORITHM_ENTRY_POINT || 'index.js'
};
```
I will have to override these defaults envs if I want to change the location
___
*[core/algorithm-gateway/algorithm_unique_folder/index.js, line 20 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KUPFw7XWGIQDfUM1X:-M_VYvDlExdnvWv4LP5O:b-9i7tpz) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/algorithm_unique_folder/index.js#L20)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Can there be a race condition between `this._resolve = res` and `return this._resolve();`?
</blockquote></details>

I don't think so, because nodeJS is single-threaded
___
*[core/algorithm-gateway/algorithm_unique_folder/index.js, line 23 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KUGJv2aJzh0xQpLs1:-M_V_5ii2LZgmiQHd2qi:b-90ytlj) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/algorithm_unique_folder/index.js#L23)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

reject is not used
</blockquote></details>

Yes, for now
___
*[core/algorithm-gateway/algorithm_unique_folder/index.js, line 43 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KUeYf2ZewXACKI_3m:-M_Vlv84EYeT7s2xokug:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/algorithm_unique_folder/index.js#L43)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Why throw -> catch -> throw?
</blockquote></details>

Done.
___
*[core/algorithm-gateway/lib/app.js, line 8 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KbkBMB_bsfKM2IOA2:-M_VbwJsEEQzEbP4VcuB:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/lib/app.js#L8)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is this just for unit tests? Maybe create a class so it can be a member or property?
</blockquote></details>

Done.
___
*[core/algorithm-operator/lib/reconcile/algorithm-gateway.js, line 13 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KdFQJ0jRnVPrKhve6:-M_VnKRv-yHhdszU75Yu:b-njpv6u) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-operator/lib/reconcile/algorithm-gateway.js#L13)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

The debug-worker has also `updated` test
`const updated = deployments.filter(d => _filterChangedDeployments(d, algorithms, versions, registry, clusterOptions, options));`
Maybe we need it here as well?
</blockquote></details>

The `updated` is related to `deployments`, but the `gateways` aren't `deployments`, they are `jobs` created inside the `task executor`
___
*[core/api-server/api/rest-api/internal/exec.js, line 18 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_Ki7T9CSvuvzzTqubb:-M_Vcg6t86RYJVH4ASvJ:b-mhf35d) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/api-server/api/rest-api/internal/exec.js#L18)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> res.gateways
> ```
Is this used? Also is `res.jobId` used? I think we used it in the past for logging or something like that, but I can't find it in the code
</blockquote></details>

We are using it for logging, but the `res.gateways` is just Golan's copy-paste
___
*[core/api-server/lib/service/gateway.js, line 17 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KjYOi9fcycDjU5n_Y:-M_VdzbL0B0onfH54swI:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/api-server/lib/service/gateway.js#L17)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> 'gateway'
> ```
use nodeKind.Gateway
</blockquote></details>

Done.
___
*[core/api-server/tests/exec-pipelines.js, line 21 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KmEen06W34YcPyAjX:-M_VkT6c3MrLoAg5ekCV:b-ta6yca) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/api-server/tests/exec-pipelines.js#L21)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why double quotes? 
</blockquote></details>

There is no formatting for tests, fixing this....
___
*[core/worker/lib/states/stateManager.js, line 202 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_Knh4E0pf3NJ3aaCB2:-M_VkqzL4BQoRsxN40Pk:b2vghai) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/worker/lib/states/stateManager.js#L202)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

What is this if for? In what case does `done` gets called when in results state
</blockquote></details>

I don't remember the exact scenario, but this error of `invalid transition` happens all the time.
during stop or exit... you will see an error in dashboard `unhandledRejection: cannot read prop data of undefined`


<!-- Sent from Reviewable.io -->

2021-05-12 14:19 UTC, yehiyam requested changes
> Reviewed 31 of 31 files at r11, 1 of 1 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1234)* status: 140 of 141 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-gateway/algorithm_unique_folder/index.js, line 1 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KT6HbCzsgUwA5cbp0:-M_Vqm9k78wCB6dcve5W:bqifx8o) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/algorithm_unique_folder/index.js#L1)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

The `nodejs-wrapper` has a config like this:
```
config.algorithm = {
    path: process.env.ALGORITHM_PATH || 'algorithm_unique_folder',
    entryPoint: process.env.ALGORITHM_ENTRY_POINT || 'index.js'
};
```
I will have to override these defaults envs if I want to change the location

</blockquote></details>

algorunner.Run accepts callback object that you can pass it the start method
___
*[core/algorithm-gateway/algorithm_unique_folder/index.js, line 20 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KUPFw7XWGIQDfUM1X:-M_Vr5gS8eg8IQ6Fg64A:b-qv71lk) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/algorithm_unique_folder/index.js#L20)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I don't think so, because nodeJS is single-threaded
</blockquote></details>

` this._resolve = res;` is called in next tick


<!-- Sent from Reviewable.io -->

2021-05-12 14:41 UTC, NassiHarel reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1234)* status: 137 of 141 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/algorithm-operator/lib/templates/algorithm-gateway.js, line 57 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KfQjVB9OvJShmu3SF:-M_W0K9JCvszWqZYbNLB:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-operator/lib/templates/algorithm-gateway.js#L57)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

shouldn't it be gatewayName?
</blockquote></details>

Done.
___
*[core/algorithm-gateway/algorithm_unique_folder/index.js, line 1 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KT6HbCzsgUwA5cbp0:-M_W0N5583QjhbAV-xsC:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/algorithm_unique_folder/index.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

algorunner.Run accepts callback object that you can pass it the start method
</blockquote></details>

Done.
___
*[core/algorithm-gateway/algorithm_unique_folder/index.js, line 20 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1234#-M_KUPFw7XWGIQDfUM1X:-M_VyT6C6R1JJ8rAljS9:b-z6su65) ([raw file](https://github.com/kube-hpc/hkube/blob/70e43ada559bf7bcb28477647fe886787f5d0670/core/algorithm-gateway/algorithm_unique_folder/index.js#L20)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

` this._resolve = res;` is called in next tick
</blockquote></details>

I think this code is synced (runs in one tick)
Can you verify this? because I tried to simulate this without success...


```
 setInterval(() => {
        events.emit('stop');
   }, 0);

 setTimeout(() => {
        events.emit('stop');
  }, 0);

 setImmediate(() => {
        events.emit('stop');
  });

 process.nextTick(() => {
        events.emit('stop');
  });

events.on('stop', () => {
         if (!this._resolve) {
            console.error('ooops');  // never happens
        }
        return this._resolve();
 });

return new Promise((res, rej) => {
        this._resolve = res;
        this._reject = rej;
    });
```


<!-- Sent from Reviewable.io -->

2021-05-13 06:32 UTC, yehiyam approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r14, 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1234#-:-M_ZQL4u2srEmbXZCglN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)



<!-- Sent from Reviewable.io -->

2021-05-13 06:45 UTC, merged