algorithm-debug
kube-HPC/hkube pull request #1264
Opened 2021-05-13 12:44 UTC by golanha

2021-05-19 07:06 UTC, NassiHarel requested changes
> Reviewed 29 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 28 of 31 files reviewed, 12 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/package.json, line 16 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2QzAADz6lWCyiu66J:-Ma2QzAADz6lWCyiu66K:b-fwgqpy) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/package.json#L16)):*
> ```
> "@hkube/uid"
> ```
in use?
___
*[core/algorithm-debug/package.json, line 23 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2QvRC43u7KUbVxMJd:-Ma2QvRC43u7KUbVxMJe:b-fvp0je) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/package.json#L23)):*
> ```
> "http-status-codes":
> ```

in use?
___
*[core/algorithm-debug/lib/index.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2OZc57FmSs360ndJJ:-Ma2OZc6CMsfaVmmXI_4:bd1ci8) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/index.js#L20)):*
> ```
>     ws.on('return', (value) => {
>         return this._resolve(value);
>     });
> ```

Is this for tests only?
___
*[core/algorithm-debug/lib/index.js, line 24 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2Odbj0IVcjPBlHT0R:-Ma2Odbj0IVcjPBlHT0S:b-z4y564) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/index.js#L24)):*
> ```
> if (options.kind === 'stream')
> ```

Use const
___
*[core/algorithm-debug/lib/index.js, line 27 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2Ok90--nZm5H2DyE-:-Ma2Ok90--nZm5H2DyE0:brq587y) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/index.js#L27)):*
> ```
> 'message',
> ```

Use const
___
*[core/algorithm-debug/lib/algorithm-communication/schema.js, line 52 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2O1YO9FQiWqjmz3vE:-Ma2O1YO9FQiWqjmz3vF:b-xcjwoi) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/schema.js#L52)):*
> ```
>     workerCommunicationSchema,
>     loopbackWorkerCommunicationSchema
> ```

are these in use?
___
*[core/algorithm-debug/lib/algorithm-communication/consts/component-names.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2MA8N5l0nBRvzsfLR:-Ma2MA8N5l0nBRvzsfLS:b-7u2vw4) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/consts/component-names.js#L5)):*
> ```
> const Components = {
> ```

Remove unnecessary
___
*[core/algorithm-debug/lib/algorithm-communication/consts/index.js, line 7 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2MPOjDgIE5aVuAwI_:-Ma2MPOjDgIE5aVuAwIa:b-c7wnkx) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/consts/index.js#L7)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     adapters: {
>         ws: 'ws',
>         socket: 'socket',
>         loopback: 'loopback'
>     }
> ```
</details>


Remove unnecessary
___
*[core/algorithm-debug/lib/errors/InvalidDataError.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2McTb5oLiNR8xFO1z:-Ma2McTb5oLiNR8xFO2-:bcrod6i) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/errors/InvalidDataError.js#L5)):*
> ```JavaScript
>         super(message);
>         this.status = 400;
>     }
> ```



Is this class in use?
___
*[core/algorithm-debug/lib/errors/index.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2MkDe2kKrF1U6J3kB:-Ma2MkDe2kKrF1U6J3kC:bal1zoa) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/errors/index.js#L5)):*
> ```JavaScript
> module.exports = {
>     InvalidDataError
> };
> ```

is this class in use?
___
*[core/algorithm-debug/tests/debug.js, line 31 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2NFE01s7ufJVqtISn:-Ma2NFE01s7ufJVqtISo:bnymjda) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/tests/debug.js#L31)):*
> ```
> const decodedData = new Encoding({ type: 'bson' })
> ```

Create this only once, in the upper scope
___
*[core/algorithm-debug/tests/debug.js, line 83 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2NgcZ5wqLRk_dChsZ:-Ma2NgcZ5wqLRk_dChs_:bcte1kz) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/tests/debug.js#L83)):*
> ```
>             if (decodedData.command === 'message') {
>                 resolveMessage();
>             }
> ```
Check also the correctness of the arrived data 


<!-- Sent from Reviewable.io -->

2021-05-19 09:28 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 22 of 31 files reviewed, 12 unresolved discussions (waiting on @NassiHarel)

___
*[core/algorithm-debug/package.json, line 16 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2QzAADz6lWCyiu66J:-Ma2YTsr9wy04sNL-7R_:b-jqj666) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/package.json#L16)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> "@hkube/uid"
> ```
in use?
</blockquote></details>

used in tests in jobs.js
___
*[core/algorithm-debug/package.json, line 23 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2QvRC43u7KUbVxMJd:-Ma2YotX-NqrtUp8UBfY:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/package.json#L23)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> "http-status-codes":
> ```

in use?
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2OZc57FmSs360ndJJ:-Ma2Z0geDOciKPoZQLQJ:bo7j6oc) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/index.js#L20)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     ws.on('return', (value) => {
>         return this._resolve(value);
>     });
> ```

Is this for tests only?
</blockquote></details>

No, this will have to be implemented on the Wrapper side
___
*[core/algorithm-debug/lib/index.js, line 24 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2Odbj0IVcjPBlHT0R:-Ma2_HtiEtXcMZzbxaPG:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/index.js#L24)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if (options.kind === 'stream')
> ```

Use const
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 27 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2Ok90--nZm5H2DyE-:-Ma2anl8-fNl53Mgkf1Y:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/index.js#L27)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> 'message',
> ```

Use const
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/algorithm-communication/schema.js, line 52 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2O1YO9FQiWqjmz3vE:-Ma2wKwgErbF6IP6OEGV:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/schema.js#L52)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     workerCommunicationSchema,
>     loopbackWorkerCommunicationSchema
> ```

are these in use?
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/algorithm-communication/consts/component-names.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2MA8N5l0nBRvzsfLR:-Ma2ec9v7r8YD1Q8FmtP:b-qddj0g) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/consts/component-names.js#L5)):*
> ```
> const Components = {
> ```
main and communication in use, removing the rest
___
*[core/algorithm-debug/lib/algorithm-communication/consts/index.js, line 7 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2MPOjDgIE5aVuAwI_:-Ma2wQ7MCVOeTKwAzASI:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/consts/index.js#L7)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     adapters: {
>         ws: 'ws',
>         socket: 'socket',
>         loopback: 'loopback'
>     }
> ```

Remove unnecessary
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/errors/InvalidDataError.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2McTb5oLiNR8xFO1z:-Ma2ezB30512wWXBDmVx:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/errors/InvalidDataError.js#L5)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Is this class in use?
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/errors/index.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2MkDe2kKrF1U6J3kB:-Ma2wUs753pQXqwuyFTs:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/errors/index.js#L5)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

is this class in use?
</blockquote></details>

Done.
___
*[core/algorithm-debug/tests/debug.js, line 31 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2NFE01s7ufJVqtISn:-Ma2tZil7HXTxEWoiIam:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/tests/debug.js#L31)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const decodedData = new Encoding({ type: 'bson' })
> ```

Create this only once, in the upper scope
</blockquote></details>

Done.
___
*[core/algorithm-debug/tests/debug.js, line 83 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2NgcZ5wqLRk_dChsZ:-Ma2vp_G4DWB7HA7QhSG:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/tests/debug.js#L83)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>             if (decodedData.command === 'message') {
>                 resolveMessage();
>             }
> ```
Check also the correctness of the arrived data 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 07:13 UTC, NassiHarel requested changes
> Reviewed 4 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 26 of 32 files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/lib/algorithm-communication/consts/index.js, line 7 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2MPOjDgIE5aVuAwI_:-Ma7bcxX4KicbCuYGQjh:b-uez90s) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/consts/index.js#L7)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You need only `ws`
___
*[core/algorithm-debug/lib/consts/messages.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma7bSB6AL23G0Vh-q5p:-Ma7bSB6AL23G0Vh-q5q:b-wkup31) ([raw file](https://github.com/kube-hpc/hkube/blob/64cd8511b6a3d5e198ded66a383ca0dd87be1911/core/algorithm-debug/lib/consts/messages.js#L1)):*
> ```
> module.exports = {
> ```

Do you need all these consts?
___
*[core/algorithm-debug/tests/debug.js, line 31 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2NFE01s7ufJVqtISn:-Ma7bIAk2qXYuB0VGIoS:b-q1d34p) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/tests/debug.js#L31)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You still have `new Encoding`


<!-- Sent from Reviewable.io -->

2021-05-20 07:23 UTC, NassiHarel requested changes
> Reviewed 2 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 28 of 32 files reviewed, 5 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/lib/index.js, line 26 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma7dta7DA8trHMsd_SP:-Ma7dta8CGaxsQcDphmq:b-5c0b9n) ([raw file](https://github.com/kube-hpc/hkube/blob/64cd8511b6a3d5e198ded66a383ca0dd87be1911/core/algorithm-debug/lib/index.js#L26)):*
> ```
> (message, origin)
> ```

This is not the right function signature
___
*[core/algorithm-debug/tests/debug.js, line 83 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2NgcZ5wqLRk_dChsZ:-Ma7d52N3irsXxPuNlhP:b6kbrnl) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/tests/debug.js#L83)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You checked the `payload`, what about the `origin`? 


<!-- Sent from Reviewable.io -->

2021-05-20 08:52 UTC, NassiHarel requested changes
> Reviewed 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 28 of 32 files reviewed, 7 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 91 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma7yCVVDkWSYCuS3hvi:-Ma7yCVVDkWSYCuS3hvj:bv4etwk) ([raw file](https://github.com/kube-hpc/hkube/blob/4dd8ee3b702d48109c553713fe62109470df200a/core/algorithm-debug/lib/algorithm-communication/ws.js#L91)):*
> ```
>  await connectedPromise;
> ```

But you are not waiting for this inside `index.js`
___
*[core/algorithm-debug/lib/algorithm-communication/consts/index.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma7u2fT30NbH2C-4hNy:-Ma7u2fUEghv8u_j7lvJ:bf814w5) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/consts/index.js#L5)):*
> ```
> adapters
> ```

Actually, `adapters` is not in use


<!-- Sent from Reviewable.io -->

2021-05-20 12:47 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 28 of 32 files reviewed, 7 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/lib/index.js, line 26 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma7dta7DA8trHMsd_SP:-Ma7mnY09fKgtE72990Q:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/046aa9644d9f135a0b9fef51d8e0e71cf650b6db/core/algorithm-debug/lib/index.js#L26)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> (message, origin)
> ```

This is not the right function signature
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/algorithm-communication/consts/index.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma7u2fT30NbH2C-4hNy:-Ma8oG6S1Qe037O18WG4:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/consts/index.js#L5)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> adapters
> ```

Actually, `adapters` is not in use

</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/algorithm-communication/consts/index.js, line 7 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2MPOjDgIE5aVuAwI_:-Ma7n-kp0pCmY03DqqfB:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/lib/algorithm-communication/consts/index.js#L7)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

You need only `ws`
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/consts/messages.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma7bSB6AL23G0Vh-q5p:-Ma7nmkE0d5__OjmYiyl:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/046aa9644d9f135a0b9fef51d8e0e71cf650b6db/core/algorithm-debug/lib/consts/messages.js#L1)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> module.exports = {
> ```

Do you need all these consts?
</blockquote></details>

Done.
___
*[core/algorithm-debug/tests/debug.js, line 31 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2NFE01s7ufJVqtISn:-Ma7kQeL0SMum9WrWvbw:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/tests/debug.js#L31)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

You still have `new Encoding`
</blockquote></details>

Done.
___
*[core/algorithm-debug/tests/debug.js, line 83 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma2NgcZ5wqLRk_dChsZ:-Ma7no3-8he23rxxrBds:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffa6e04a8d786710c44e926863929b73eb7cdf62/core/algorithm-debug/tests/debug.js#L83)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

You checked the `payload`, what about the `origin`? 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 12:49 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 28 of 32 files reviewed, 7 unresolved discussions (waiting on @NassiHarel)

___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 91 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Ma7yCVVDkWSYCuS3hvi:-Ma8oPmC5TvQdYt55TeX:bv82ycg) ([raw file](https://github.com/kube-hpc/hkube/blob/4dd8ee3b702d48109c553713fe62109470df200a/core/algorithm-debug/lib/algorithm-communication/ws.js#L91)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  await connectedPromise;
> ```

But you are not waiting for this inside `index.js`

</blockquote></details>

I want the send action itself to delay to when the debugged algorithm is connecting.


<!-- Sent from Reviewable.io -->

2021-05-26 13:39 UTC, NassiHarel requested changes
> Reviewed 6 of 29 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 30 of 54 files reviewed, 10 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/api-server/lib/service/algorithmBase.js, line 10 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MacsI746dxhrZiTdVHd:-MacsI755kQZXTK4AkK8:b-tnqax9) ([raw file](https://github.com/kube-hpc/hkube/blob/2465e2c032022d9737b59217a04916c255dd59c4/core/api-server/lib/service/algorithmBase.js#L10)):*
> ```
>  this._gatewayUrl = config.gatewayUrl.path;
> ```
??
___
*[core/task-executor/lib/helpers/etcd.js, line 89 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mact1kW4ACX6jX88ObQ:-Mact1kW4ACX6jX88ObR:b-zi6wr6) ([raw file](https://github.com/kube-hpc/hkube/blob/9893d0133d039d114e099d94914034cd4a0a6e5e/core/task-executor/lib/helpers/etcd.js#L89)):*
> ```
> options.debug
> ```
Find all places we are doing `.debug`
___
*[core/task-executor/lib/templates/service.js, line 68 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MactElT0m7MvrUNkLxi:-MactElT0m7MvrUNkLxj:bu9k4vu) ([raw file](https://github.com/kube-hpc/hkube/blob/2465e2c032022d9737b59217a04916c255dd59c4/core/task-executor/lib/templates/service.js#L68)):*
> ```
>     workerIngress,
>     workerService
> ```

this shouldn't be here, should be like gateways


<!-- Sent from Reviewable.io -->

2021-05-26 13:48 UTC, NassiHarel reviewed
> Reviewed 12 of 29 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 41 of 54 files reviewed, 10 unresolved discussions (waiting on @golanha and @NassiHarel)



<!-- Sent from Reviewable.io -->

2021-05-26 13:50 UTC, NassiHarel reviewed
> Reviewed 1 of 6 files at r4, 4 of 29 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 46 of 54 files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)



<!-- Sent from Reviewable.io -->

2021-05-26 13:52 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 46 of 54 files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/api-server/lib/service/debug.js, line 36 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Macwl9042fRq6Y8Ukgu:-Macwl91EYcxEzn6h1Vr:bgqe1kd) ([raw file](https://github.com/kube-hpc/hkube/blob/8825aa93e70ff78826a24d697b1feb2b34688389/core/api-server/lib/service/debug.js#L36)):*
> ```
> :v2.0.2
> ```
??


<!-- Sent from Reviewable.io -->

2021-05-27 05:33 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 43 of 54 files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/service/algorithmBase.js, line 10 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MacsI746dxhrZiTdVHd:-MagAFhh1IpRN544ZV1u:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2465e2c032022d9737b59217a04916c255dd59c4/core/api-server/lib/service/algorithmBase.js#L10)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  this._gatewayUrl = config.gatewayUrl.path;
> ```
??
</blockquote></details>

Done.
___
*[core/api-server/lib/service/debug.js, line 36 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Macwl9042fRq6Y8Ukgu:-MagIsg35tDbsYT14jg_:b61jec) ([raw file](https://github.com/kube-hpc/hkube/blob/8825aa93e70ff78826a24d697b1feb2b34688389/core/api-server/lib/service/debug.js#L36)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> :v2.0.2
> ```
??
</blockquote></details>

I leave it hard coded until help is updated
___
*[core/task-executor/lib/helpers/etcd.js, line 89 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mact1kW4ACX6jX88ObQ:-MagCQSL1cMD43Vr3wOz:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9893d0133d039d114e099d94914034cd4a0a6e5e/core/task-executor/lib/helpers/etcd.js#L89)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> options.debug
> ```
Find all places we are doing `.debug`
</blockquote></details>

Done.
___
*[core/task-executor/lib/templates/service.js, line 68 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MactElT0m7MvrUNkLxi:-MagCWuUC-7WAIOsbzGT:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2465e2c032022d9737b59217a04916c255dd59c4/core/task-executor/lib/templates/service.js#L68)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     workerIngress,
>     workerService
> ```

this shouldn't be here, should be like gateways
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-01 07:53 UTC, NassiHarel requested changes
> Reviewed 1 of 29 files at r5, 2 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 46 of 56 files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/api-server/lib/service/debug.js, line 5 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mb5YuIS-gPsLVfURKGM:-Mb5YuIS-gPsLVfURKGN:baozop4) ([raw file](https://github.com/kube-hpc/hkube/blob/1cf62504cd542135d9f92152cb4f0ce6e89124ef/core/api-server/lib/service/debug.js#L5)):*
> ```JavaScript
> const stateManager = require('../state/state-manager');
> const AlgorithmBase = require('./algorithmBase');
> ```

Remove debug ref in worker
___
*[core/task-executor/lib/helpers/etcd.js, line 89 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mact1kW4ACX6jX88ObQ:-Mb5Yo_e4xTDXyRuZ5pJ:b-rxnrlf) ([raw file](https://github.com/kube-hpc/hkube/blob/9893d0133d039d114e099d94914034cd4a0a6e5e/core/task-executor/lib/helpers/etcd.js#L89)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

try to find more...


<!-- Sent from Reviewable.io -->

2021-06-02 14:39 UTC, golanha commented
/deploy

2021-06-03 07:02 UTC, golanha commented
/deploy

2021-06-03 07:23 UTC, golanha commented
/deploy

2021-06-03 07:55 UTC, golanha commented
/deploy

2021-06-03 08:56 UTC, golanha commented
/deploy

2021-06-03 09:35 UTC, golanha commented
/deply

2021-06-03 10:09 UTC, golanha commented
/deploy

2021-06-09 06:05 UTC, golanha commented
/deploy

2021-06-13 06:31 UTC, golanha commented
/deploy

2021-06-13 09:12 UTC, golanha commented
/deploy

2021-06-13 11:06 UTC, golanha commented
/deploy

2021-06-13 11:55 UTC, golanha commented
/deploy

2021-06-13 12:54 UTC, golanha commented
/deploy

2021-06-13 13:58 UTC, golanha commented
/deploy

2021-06-13 14:17 UTC, golanha commented
/deploy

2021-06-14 11:05 UTC, golanha commented
/deploy

2021-06-15 07:52 UTC, golanha commented
/deploy

2021-06-15 08:34 UTC, golanha commented
deploy

2021-06-15 08:34 UTC, golanha commented
/deploy

2021-06-16 08:07 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 33 of 76 files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/service/debug.js, line 5 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mb5YuIS-gPsLVfURKGM:-McIBwWV1rnqqyrZLPzJ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/1cf62504cd542135d9f92152cb4f0ce6e89124ef/core/api-server/lib/service/debug.js#L5)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Remove debug ref in worker
</blockquote></details>

Done.
___
*[core/task-executor/lib/helpers/etcd.js, line 89 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mact1kW4ACX6jX88ObQ:-McIC1tdEoUjMD6vj8kc:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9893d0133d039d114e099d94914034cd4a0a6e5e/core/task-executor/lib/helpers/etcd.js#L89)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

try to find more...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-16 10:15 UTC, NassiHarel requested changes
> Reviewed 1 of 29 files at r5, 1 of 1 files at r6, 1 of 6 files at r7, 1 of 3 files at r8, 38 of 39 files at r9.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 75 of 76 files reviewed, 11 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/lib/index.js, line 17 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJJNSB1Eu5ZN5HzoTz:-McJJNSB1Eu5ZN5HzoU-:brsg3to) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L17)):*
> ```JavaScript
>     });
>     this.prevMessageDone = null;
> };
> ```

Don't forget to work on the UI
___
*[core/algorithm-operator/lib/deployments/algorithm-debug.js, line 4 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJA7v11t0fDMOU9UPL:-McJA7v11t0fDMOU9UPM:b-79lgtg) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-operator/lib/deployments/algorithm-debug.js#L4)):*
> ```
> algorithmName.substr(0, algorithmName.lastIndexOf('-debug'));
> ```
Why it's not like the `gateway`, cleaner...
___
*[core/algorithm-operator/lib/reconcile/algorithm-debug.js, line 13 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJAK1C1sMBjh24yvVg:-McJAK1C1sMBjh24yvVh:b-y8q9gz) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-operator/lib/reconcile/algorithm-debug.js#L13)):*
> ```
>     const added = debugAlgorithms.filter(a => !normServices.find(d => `${d.algorithmName}-debug` === a.name));
>     const removed = normServices.filter(d => !debugAlgorithms.find(a => `${d.algorithmName}-debug` === a.name));
> ```

Why it's not like the `gateway`, cleaner...
___
*[core/algorithm-operator/lib/templates/algorithm-debug.js, line 21 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJCEy1C-c3p2Qrx2iJ:-McJCEy1C-c3p2Qrx2iK:b-5v59iz) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-operator/lib/templates/algorithm-debug.js#L21)):*
> ```
> `${algorithmName}-debug`,
> ```
not like gateway
___
*[core/api-server/lib/service/execution.js, line 124 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McIn28oD_zLdq0ZNCPt:-McIn28oD_zLdq0ZNCPu:bav3srm) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/execution.js#L124)):*
> ```
> kind === 'debug'
> ```
Find and replace all 'debug' with @hkube/consts nodeKind.debug
___
*[core/api-server/lib/service/gateway.js, line 6 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McInGWvBSXK8jPdGupf:-McInGWvBSXK8jPdGupg:bu3iq6f) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/gateway.js#L6)):*
> ```JavaScript
> const { InvalidDataError } = require('../errors');
> const stateManager = require('../state/state-manager');
> const AlgorithmBase = require('./algorithmBase');
> ```

There should be an empty line here
___
*[core/api-server/lib/service/pipeline-creator.js, line 103 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJI_i58Xfu6fvWoNc5:-McJI_i58Xfu6fvWoNc6:bz094k0) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/pipeline-creator.js#L103)):*
> ```
> const { algorithmName } = node;
> ```

What will happen if the user will not provide `algorithmName`?
___
*[core/api-server/lib/service/pipeline-creator.js, line 108 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McInkUG-FJm5Ner9GRs:-McInkUG-FJm5Ner9GRt:b-vx7exz) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/pipeline-creator.js#L108)):*
> ```
> { ...pipeline };
> ```

the `...` is meaningless here
___
*[core/api-server/lib/state/state-manager.js, line 51 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McInyfv9zmxsIm5CMpO:-McInyfv9zmxsIm5CMpP:b-3v9d1j) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/state/state-manager.js#L51)):*
> ```
> // TODO 
> ```
Remove todo
___
*[core/task-executor/lib/reconcile/reconciler.js, line 578 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJDBaU5hCh5-jikC3N:-McJDBaU5hCh5-jikC3O:b-dwedpj) ([raw file](https://github.com/kube-hpc/hkube/blob/d4666e27766a9e89107963dc45ce8bfd9a6c1f10/core/task-executor/lib/reconcile/reconciler.js#L578)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     const resourcesToFree = skipped.reduce((prev, cur) => {
>         return {
>             cpu: prev.cpu + cur.resourceRequests.requests.cpu,
>             gpu: prev.gpu + cur.resourceRequests.requests[gpuVendors.NVIDIA],
>             memory: prev.memory + parse.getMemoryInMi(cur.resourceRequests.requests.memory)
>         };
>     }, { cpu: 0, gpu: 0, memory: 0 });
> ```
</details>


Who removed this code?


<!-- Sent from Reviewable.io -->

2021-06-16 12:44 UTC, NassiHarel requested changes
> Reviewed 1 of 39 files at r9.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 16 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/lib/index.js, line 9 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJo28L9r-HHrbi4mwt:-McJo28M-WPmdiSmp2Dy:btlcgwp) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L9)):*
> ```
> const log = Logger.GetLogFromContainer();
> ```

You can do 
`const Logger = require('@hkube/logger').GetLogFromContainer();`
___
*[core/algorithm-debug/lib/index.js, line 18 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJoIwSC7CONkbKJG08:-McJoIwSC7CONkbKJG09:b3rkqob) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L18)):*
> ```
> // eslint-disable-line consistent-return
> ```
Do you need this comment?
___
*[core/algorithm-debug/lib/index.js, line 20 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJoCFp2YKIw5mYEpdM:-McJoCFp2YKIw5mYEpdN:b-k8tz4s) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L20)):*
> ```
> log.info(`input:${options.input[0]}`);
> ```
Do you need to print that? it maybe very large object
___
*[core/algorithm-debug/lib/index.js, line 35 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJqENUBILTZ7yJE0gx:-McJqENVBzVoH97cnyxF:bcya1pp) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L35)):*
> ```
> if (this.prevMessageDone != null) {
> ```

`if (this.prevMessageDone) `
___
*[core/algorithm-debug/lib/index.js, line 57 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJqJy-A9Vl5E1Iz5zr:-McJqJy-A9Vl5E1Iz5zs:b-lk1v02) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L57)):*
> ```
>  if (this.prevMessageDone != null)
> ```
`if (this.prevMessageDone) `


<!-- Sent from Reviewable.io -->

2021-06-16 13:56 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 66 of 79 files reviewed, 15 unresolved discussions (waiting on @NassiHarel)

___
*[core/algorithm-debug/lib/index.js, line 9 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJo28L9r-HHrbi4mwt:-McJzAWD5I-HlvLXfjMp:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L9)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const log = Logger.GetLogFromContainer();
> ```

You can do 
`const Logger = require('@hkube/logger').GetLogFromContainer();`
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 17 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJJNSB1Eu5ZN5HzoTz:-McJkBIj5Q9FGFTqI_8z:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L17)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Don't forget to work on the UI
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 18 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJoIwSC7CONkbKJG08:-McJzX242YTJhHtuPJeZ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L18)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> // eslint-disable-line consistent-return
> ```
Do you need this comment?
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 20 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJoCFp2YKIw5mYEpdM:-McJzcnO43Mqig40vqMx:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L20)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> log.info(`input:${options.input[0]}`);
> ```
Do you need to print that? it maybe very large object
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 35 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJqENUBILTZ7yJE0gx:-McK-2fr76RTtn0szhK0:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L35)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if (this.prevMessageDone != null) {
> ```

`if (this.prevMessageDone) `
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 57 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJqJy-A9Vl5E1Iz5zr:-McK-4Y67pD0LLuIV7cZ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-debug/lib/index.js#L57)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  if (this.prevMessageDone != null)
> ```
`if (this.prevMessageDone) `
</blockquote></details>

Done.
___
*[core/algorithm-operator/lib/deployments/algorithm-debug.js, line 4 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJA7v11t0fDMOU9UPL:-McJXxoI40-ZARWrjV0-:bo1ex3) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-operator/lib/deployments/algorithm-debug.js#L4)):*
> algorithmName.substr(0, algorithmName.lastIndexOf('-debug'))
Because in debug there is not attribute such as "gatewayName" , a short simple name without the word gateway. 
In gateway we use the gateway name at the end of the url.
I didn't want the url to look like: hkube/debug/xxxx-debug
hkube/debug/xxxx is enough.
___
*[core/algorithm-operator/lib/reconcile/algorithm-debug.js, line 13 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJAK1C1sMBjh24yvVg:-McK2k71CdqAoktxgXIs:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-operator/lib/reconcile/algorithm-debug.js#L13)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     const added = debugAlgorithms.filter(a => !normServices.find(d => `${d.algorithmName}-debug` === a.name));
>     const removed = normServices.filter(d => !debugAlgorithms.find(a => `${d.algorithmName}-debug` === a.name));
> ```

Why it's not like the `gateway`, cleaner...
</blockquote></details>

Done.
___
*[core/algorithm-operator/lib/templates/algorithm-debug.js, line 21 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJCEy1C-c3p2Qrx2iJ:-McK2xqv-9V5U6Mxk45t:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-operator/lib/templates/algorithm-debug.js#L21)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> `${algorithmName}-debug`,
> ```
not like gateway
</blockquote></details>

Done.
___
*[core/api-server/lib/service/execution.js, line 124 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McIn28oD_zLdq0ZNCPt:-McK3DeTDa84tmqmvwgL:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/execution.js#L124)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> kind === 'debug'
> ```
Find and replace all 'debug' with @hkube/consts nodeKind.debug
</blockquote></details>

Done.
___
*[core/api-server/lib/service/gateway.js, line 6 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McInGWvBSXK8jPdGupf:-McJsjbvAv6m3tRv1DwW:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/gateway.js#L6)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

There should be an empty line here
</blockquote></details>

Done.
___
*[core/api-server/lib/service/pipeline-creator.js, line 103 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJI_i58Xfu6fvWoNc5:-McJtiCoCDHwHoKi0HnG:bxohovp) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/pipeline-creator.js#L103)):*
> const { algorithmName } = node
its not like gatewayName, pipeline would fail validation if it was applied with empty algorithmName
___
*[core/api-server/lib/service/pipeline-creator.js, line 108 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McInkUG-FJm5Ner9GRs:-McJugYh9KKj88SN74qp:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/pipeline-creator.js#L108)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> { ...pipeline };
> ```

the `...` is meaningless here
</blockquote></details>

Done.
___
*[core/api-server/lib/state/state-manager.js, line 51 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McInyfv9zmxsIm5CMpO:-McK3AXT8R-rtc0Ah2IM:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/state/state-manager.js#L51)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> // TODO 
> ```
Remove todo
</blockquote></details>

Done.
___
*[core/task-executor/lib/reconcile/reconciler.js, line 578 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJDBaU5hCh5-jikC3N:-McK3BwVD1t2r13rn6Pk:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d4666e27766a9e89107963dc45ce8bfd9a6c1f10/core/task-executor/lib/reconcile/reconciler.js#L578)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     const resourcesToFree = skipped.reduce((prev, cur) => {
>         return {
>             cp [...]

2021-06-16 14:07 UTC, golanha commented
___
*[core/task-executor/lib/reconcile/reconciler.js, line 578 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJDBaU5hCh5-jikC3N:-McK8Ggl6UVbmvqUMR6A:b-q2802i) ([raw file](https://github.com/kube-hpc/hkube/blob/d4666e27766a9e89107963dc45ce8bfd9a6c1f10/core/task-executor/lib/reconcile/reconciler.js#L578)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Deep scan found it was not used, this is why I removed it


<!-- Sent from Reviewable.io -->

2021-06-17 11:00 UTC, NassiHarel requested changes
> Reviewed 14 of 14 files at r10.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 7 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-operator/lib/deployments/algorithm-debug.js, line 4 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJA7v11t0fDMOU9UPL:-McOb3hz71Qec_YeEKp4:bnz7gn8) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-operator/lib/deployments/algorithm-debug.js#L4)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> algorithmName.substr(0, algorithmName.lastIndexOf('-debug'))
Because in debug there is not attribute such as "gatewayName" , a short simple name without the word gateway. 
In gateway we use the gateway name at the end of the url.
I didn't want the url to look like: hkube/debug/xxxx-debug
hkube/debug/xxxx is enough.
</blockquote></details>


So create property `debugName `
___
*[core/algorithm-operator/lib/reconcile/algorithm-debug.js, line 12 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McObIim87JaXNXRJz-L:-McObIim87JaXNXRJz-M:bmm9ikj) ([raw file](https://github.com/kube-hpc/hkube/blob/fef928d83ccd7ac06518b8688911de3d27da71f5/core/algorithm-operator/lib/reconcile/algorithm-debug.js#L12)):*
> ```
> a.nam
> ```
???
___
*[core/api-server/api/rest-api/swagger/definitions/caching.yaml, line 12 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McOc-rODiU9i5WJ5Qox:-McOc-rODiU9i5WJ5Qoy:b-10xb47) ([raw file](https://github.com/kube-hpc/hkube/blob/fef928d83ccd7ac06518b8688911de3d27da71f5/core/api-server/api/rest-api/swagger/definitions/caching.yaml#L12)):*
> ```
> minLength: 1
> ```
I think that  minLength is for strings
___
*[core/api-server/lib/service/execution.js, line 32 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McObYwmAgF3STVxQJVO:-McObYwnAwP6KfKz-qM0:b-gyxy1l) ([raw file](https://github.com/kube-hpc/hkube/blob/fef928d83ccd7ac06518b8688911de3d27da71f5/core/api-server/lib/service/execution.js#L32)):*
> ```
> await cachingService.exec({ jobId: options.jobId, nodeName: options.nodeName, debug: options.debug
> ```

Add new unit test for this
___
*[core/api-server/lib/service/pipeline-creator.js, line 103 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJI_i58Xfu6fvWoNc5:-McObgHV8Qqji-IQOTie:b-qf250d) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/pipeline-creator.js#L103)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> const { algorithmName } = node
its not like gatewayName, pipeline would fail validation if it was applied with empty algorithmName
</blockquote></details>

But we need that pipeline will not even start if it was applied with empty algorithmName


<!-- Sent from Reviewable.io -->

2021-06-17 12:46 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 76 of 82 files reviewed, 7 unresolved discussions (waiting on @NassiHarel)

___
*[core/algorithm-operator/lib/deployments/algorithm-debug.js, line 4 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJA7v11t0fDMOU9UPL:-McOtLVP5NfUKYkZn5_A:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/algorithm-operator/lib/deployments/algorithm-debug.js#L4)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

So create property `debugName `
</blockquote></details>

Done.
___
*[core/algorithm-operator/lib/reconcile/algorithm-debug.js, line 12 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McObIim87JaXNXRJz-L:-McOvd1b4y3t4QlhqQqq:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/fef928d83ccd7ac06518b8688911de3d27da71f5/core/algorithm-operator/lib/reconcile/algorithm-debug.js#L12)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> a.nam
> ```
???
</blockquote></details>

Done.
___
*[core/api-server/api/rest-api/swagger/definitions/caching.yaml, line 12 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McOc-rODiU9i5WJ5Qox:-McOvrAv0hJjcsJTg-_i:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/fef928d83ccd7ac06518b8688911de3d27da71f5/core/api-server/api/rest-api/swagger/definitions/caching.yaml#L12)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> minLength: 1
> ```
I think that  minLength is for strings
</blockquote></details>

Done.
___
*[core/api-server/lib/service/execution.js, line 32 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McObYwmAgF3STVxQJVO:-McP-caQ1zTpPu94LXOG:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/fef928d83ccd7ac06518b8688911de3d27da71f5/core/api-server/lib/service/execution.js#L32)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> await cachingService.exec({ jobId: options.jobId, nodeName: options.nodeName, debug: options.debug
> ```

Add new unit test for this
</blockquote></details>

Done.
___
*[core/api-server/lib/service/pipeline-creator.js, line 103 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McJI_i58Xfu6fvWoNc5:-McOn7q40mezb3FoVdOJ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2f4140ad3f71927d983b2d72456901758778d17a/core/api-server/lib/service/pipeline-creator.js#L103)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

But we need that pipeline will not even start if it was applied with empty algorithmName
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-17 13:38 UTC, golanha commented
/deploy

2021-06-17 13:58 UTC, NassiHarel requested changes
> Reviewed 7 of 8 files at r11.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 81 of 82 files reviewed, 6 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/api-server/lib/validation/pipelines.js, line 24 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPDJpl45tXK3If5gzB:-McPDJpmA3TJJJFeypUV:b-btshxs) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/lib/validation/pipelines.js#L24)):*
> ```
> (!node.algorithmName || node.algorithmNam === ''))
> ```

There are 3 errors in this line:
1. This line shouldn't be here, it should be in debug service.
2. You wrote `node.algorithmNam`, without e.
3. You can write just (!node.algorithmName)
___
*[core/api-server/tests/exec-raw.js, line 41 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPE0OC9SPPhZtXjibJ:-McPE0OC9SPPhZtXjibK:b-b52x35) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/tests/exec-raw.js#L41)):*
> ```
> it('should succeed run caching with debug'
> ```
Check also that `kind` debug has been added.
___
*[core/api-server/api/rest-api/routes/v1/store.js, line 60 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPEHa03hRZ41uGi_ws:-McPEHa03hRZ41uGi_wt:b32im1n) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/api/rest-api/routes/v1/store.js#L60)):*
> ```
>  options: { debug: true }
> ```
??? options: { debug: true } ?? regression ???

What this route should do? insert debug algorithm?

Search for `runAlgorithm`, maybe we can /exec/algorithm with kind debug?
___
*[core/api-server/api/rest-api/routes/v1/store.js, line 77 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPFXPu1Kq_X1rk-xgv:-McPFXPu1Kq_X1rk-xgw:b-oanjg7) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/api/rest-api/routes/v1/store.js#L77)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     router.delete('/algorithms/debug/:name', async (req, res) => {
>         const { name } = req.params;
>         await algorithmStore.deleteAlgorithm({ name });
>         res.json({ message: 'OK' });
>     });
> ```
</details>

you can add kind `debug`.
but I don't think we need this route anymore.


<!-- Sent from Reviewable.io -->

2021-06-20 11:05 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 81 of 82 files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/lib/validation/pipelines.js, line 24 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPDJpl45tXK3If5gzB:-Mcd4AAF03aO0FlladbK:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/lib/validation/pipelines.js#L24)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> (!node.algorithmName || node.algorithmNam === ''))
> ```

There are 3 errors in this line:
1. This line shouldn't be here, it should be in debug service.
2. You wrote `node.algorithmNam`, without e.
3. You can write just (!node.algorithmName)

</blockquote></details>

Done.
___
*[core/api-server/tests/exec-raw.js, line 41 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPE0OC9SPPhZtXjibJ:-Mcd4bNv7tUM_Lgnm4pR:bdkvx7s) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/tests/exec-raw.js#L41)):*
> should succeed run caching with debug
Its checked by trying to insert another one
 " expect(response.body.error.message).eq('debug green-alg-debug already exists');"
___
*[core/api-server/api/rest-api/routes/v1/store.js, line 60 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPEHa03hRZ41uGi_ws:-Mcd52p4-1N4mirxSduu:b52gb9v) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/api/rest-api/routes/v1/store.js#L60)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  options: { debug: true }
> ```
??? options: { debug: true } ?? regression ???

What this route should do? insert debug algorithm?

Search for `runAlgorithm`, maybe we can /exec/algorithm with kind debug?
</blockquote></details>

Right, no need for this rout, removed.
___
*[core/api-server/api/rest-api/routes/v1/store.js, line 77 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPFXPu1Kq_X1rk-xgv:-Mcd45769ca_Rogooc05:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/api/rest-api/routes/v1/store.js#L77)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     router.delete('/algorithms/debug/:name', async (req, res) => {
>         const { name } = req.params;
>         await algorithmStore.deleteAlgorithm({ name });
>         res.json({ message: 'OK' });
>     });
> ```
you can add kind `debug`.
but I don't think we need this route anymore.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-21 04:47 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 81 of 82 files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/lib/validation/pipelines.js, line 24 at r11](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McPDJpl45tXK3If5gzB:-McgtIwSCH58uKr6xNTm:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/eec39adcc90650105ddac84f4b38f94cdd295d91/core/api-server/lib/validation/pipelines.js#L24)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-21 10:35 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 79 of 82 files reviewed, 5 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/api-server/lib/service/debug.js, line 19 at r12](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mci7gNd955vlBvYXlI1:-Mci7gNd955vlBvYXlI2:bbl5jsa) ([raw file](https://github.com/kube-hpc/hkube/blob/d0fe77dc87baf3b96989e2afd62054904b6454a5/core/api-server/lib/service/debug.js#L19)):*
> ```
> async createDebug({ algorithmName: originalAlgName }) {
> ```

The names are too complicated, maybe rewrite...

```
async createDebug({ algorithmName }) {
        if (!algorithmName) {
            throw new InvalidDataError('Node for debug must have algorithm name set');
        }
        const newAlgorithmName = `${algorithmName}-${this._kind}`;
        const debug = await stateManager.getAlgorithm({ name: newAlgorithmName });
        if (debug) {
            throw new InvalidDataError(`debug ${newAlgorithmName} already exists`);
        }
        const originalAlg = await stateManager.getAlgorithm({ name: algorithmName });
        if (!originalAlg) {
            throw new InvalidDataError(`debug ${algorithmName} does not exists`);
        }
        const debugUrl = `${this._debugUrl}/${algorithmName}`;
        const algorithm = {
            cpu: originalAlg.cpu,
            mem: originalAlg.mem,
            name: newAlgorithmName,
            debugUrl,
            debugName: algorithmName,
            kind: nodeKind.Debug,
            algorithmImage: 'hkube/algorithm-debug',
            type: buildTypes.IMAGE,
            options: {
                debug: false,
                pending: false
            }
        };
        await stateManager.updateAlgorithm(algorithm);
        return { newAlgorithmName, url: debugUrl };
    }
```
___
*[core/api-server/lib/service/debug.js, line 20 at r12](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mci7cXe9CQtSL6vUXT6:-Mci7cXe9CQtSL6vUXT7:bz5e0q6) ([raw file](https://github.com/kube-hpc/hkube/blob/d0fe77dc87baf3b96989e2afd62054904b6454a5/core/api-server/lib/service/debug.js#L20)):*
> ```
> if ((!originalAlgName))
> ```
???
___
*[core/api-server/lib/service/debug.js, line 43 at r12](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mci7ZJY7REt5KmqNlgl:-Mci7ZJZ-ZkQKDSpkoo5:b-nm66co) ([raw file](https://github.com/kube-hpc/hkube/blob/d0fe77dc87baf3b96989e2afd62054904b6454a5/core/api-server/lib/service/debug.js#L43)):*
> ```
> debug: false,
> ```
???


<!-- Sent from Reviewable.io -->

2021-06-21 10:44 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 79 of 82 files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/lib/service/debug.js, line 19 at r12](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mci7gNd955vlBvYXlI1:-Mci9sjY9YQrNwuuik8B:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d0fe77dc87baf3b96989e2afd62054904b6454a5/core/api-server/lib/service/debug.js#L19)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> async createDebug({ algorithmName: originalAlgName }) {
> ```

The names are too complicated, maybe rewrite...

```
async createDebug({ algorithmName }) {
        if (!algorithmName) {
            throw new InvalidDataError('Node for debug must have algorithm name set');
        }
        const newAlgorithmName = `${algorithmName}-${this._kind}`;
        const debug = await stateManager.getAlgorithm({ name: newAlgorithmName });
        if (debug) {
            throw new InvalidDataError(`debug ${newAlgorithmName} already exists`);
        }
        const originalAlg = await stateManager.getAlgorithm({ name: algorithmName });
        if (!originalAlg) {
            throw new InvalidDataError(`debug ${algorithmName} does not exists`);
        }
        const debugUrl = `${this._debugUrl}/${algorithmName}`;
        const algorithm = {
            cpu: originalAlg.cpu,
            mem: originalAlg.mem,
            name: newAlgorithmName,
            debugUrl,
            debugName: algorithmName,
            kind: nodeKind.Debug,
            algorithmImage: 'hkube/algorithm-debug',
            type: buildTypes.IMAGE,
            options: {
                debug: false,
                pending: false
            }
        };
        await stateManager.updateAlgorithm(algorithm);
        return { newAlgorithmName, url: debugUrl };
    }
```

</blockquote></details>

Done.
___
*[core/api-server/lib/service/debug.js, line 20 at r12](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mci7cXe9CQtSL6vUXT6:-Mci9F7WBxEBdWmq5gH1:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d0fe77dc87baf3b96989e2afd62054904b6454a5/core/api-server/lib/service/debug.js#L20)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> if ((!originalAlgName))
> ```
???
</blockquote></details>

Done.
___
*[core/api-server/lib/service/debug.js, line 43 at r12](https://reviewable.io/reviews/kube-hpc/hkube/1264#-Mci7ZJY7REt5KmqNlgl:-Mci93z09VZ6FiR7sksa:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d0fe77dc87baf3b96989e2afd62054904b6454a5/core/api-server/lib/service/debug.js#L43)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> debug: false,
> ```
???
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-21 11:12 UTC, NassiHarel requested changes
> Reviewed 1 of 3 files at r12, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/api-server/api/rest-api/routes/v1/store.js, line 66 at r13](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MciGKHc2YXFx4kcdns6:-MciGKHc2YXFx4kcdns7:b-9kkg22) ([raw file](https://github.com/kube-hpc/hkube/blob/6db0b3307dc9eee008540104f0bdfed02a693e81/core/api-server/api/rest-api/routes/v1/store.js#L66)):*
> ```
> router.delete('/algorithms/debug/:name', async (req, res) => {
> ```

Can be removed now...


<!-- Sent from Reviewable.io -->

2021-06-21 11:16 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/api-server/lib/service/pipeline-creator.js, line 101 at r13](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MciH6lc8xTnB2lz889M:-MciH6lc8xTnB2lz889N:b-mggoaq) ([raw file](https://github.com/kube-hpc/hkube/blob/6db0b3307dc9eee008540104f0bdfed02a693e81/core/api-server/lib/service/pipeline-creator.js#L101)):*
> ```
>                 if (!debugs) {
>                     debugs = [];
>                 }
> ```
????


<!-- Sent from Reviewable.io -->

2021-06-21 11:19 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/api-server/lib/service/pipeline-creator.js, line 109 at r13](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MciHvPv9AJUAIieVh5z:-MciHvPv9AJUAIieVh6-:b9e3z3w) ([raw file](https://github.com/kube-hpc/hkube/blob/6db0b3307dc9eee008540104f0bdfed02a693e81/core/api-server/lib/service/pipeline-creator.js#L109)):*
> ```JavaScript
>         }
>         return pipeline;
>     }
> ```

Find text with `debug:`and remove it


<!-- Sent from Reviewable.io -->

2021-06-21 12:27 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/api/rest-api/routes/v1/store.js, line 66 at r13](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MciGKHc2YXFx4kcdns6:-MciX4t166-QACQRVCwP:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/6db0b3307dc9eee008540104f0bdfed02a693e81/core/api-server/api/rest-api/routes/v1/store.js#L66)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> router.delete('/algorithms/debug/:name', async (req, res) => {
> ```

Can be removed now...
</blockquote></details>

Done.
___
*[core/api-server/lib/service/pipeline-creator.js, line 101 at r13](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MciH6lc8xTnB2lz889M:-MciXVbT98fEeGdd3qwu:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/6db0b3307dc9eee008540104f0bdfed02a693e81/core/api-server/lib/service/pipeline-creator.js#L101)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>                 if (!debugs) {
>                     debugs = [];
>                 }
> ```
????
</blockquote></details>

Done.
___
*[core/api-server/lib/service/pipeline-creator.js, line 109 at r13](https://reviewable.io/reviews/kube-hpc/hkube/1264#-MciHvPv9AJUAIieVh5z:-MciXWpDBITA20n6QVjZ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/6db0b3307dc9eee008540104f0bdfed02a693e81/core/api-server/lib/service/pipeline-creator.js#L109)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Find text with `debug:`and remove it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-21 12:53 UTC, NassiHarel requested changes
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/api-server/lib/service/pipeline-creator.js, line 96 at r14](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McicL6-EqyyrQpBBK5L:-McicL6-EqyyrQpBBK5M:b-jhrrts) ([raw file](https://github.com/kube-hpc/hkube/blob/8790fb61a618212c6b95e4103a5a9fd25a28fa40/core/api-server/lib/service/pipeline-creator.js#L96)):*
> ```JavaScript
>     }
> 
>     async updateDebug(pipeline) {
> ```

Find text with "debug:" and remove it


<!-- Sent from Reviewable.io -->

2021-06-22 10:54 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 80 of 82 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/lib/service/pipeline-creator.js, line 96 at r14](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McicL6-EqyyrQpBBK5L:-McnLmhc6TPDWhd2ij6z:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8790fb61a618212c6b95e4103a5a9fd25a28fa40/core/api-server/lib/service/pipeline-creator.js#L96)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Find text with "debug:" and remove it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-22 13:53 UTC, NassiHarel requested changes
> Reviewed 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 26 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McnyoWs-WnT43UOXVzF:-McnyoWt4UaI_Bzk3-2c:b6u9eq3) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L26)):*
> ```
> ws.on
> ```

I think that each time the `start` function is called, you are registering for events with `ws.on`.
So it might trigger these callbacks many times for one single event, didn't check it...


<!-- Sent from Reviewable.io -->

2021-06-22 15:00 UTC, golanha commented
___
*[core/algorithm-debug/lib/index.js, line 26 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McnyoWs-WnT43UOXVzF:-McoDxnkBcLnqvCV81dl:b-gafm5x) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L26)):*
> ```
>  ws.on(messages.outgoing.streamingInMessageDone, ({ sendMessageId }) => {
> ```
Line 19: "events.removeAllListeners();" So the events are not triggered many times.


<!-- Sent from Reviewable.io -->

2021-06-22 15:09 UTC, golanha commented
___
*[core/algorithm-debug/lib/index.js, line 26 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McnyoWs-WnT43UOXVzF:-McoEFk5EJ3h0c-XF6L_:b-3r3rkx) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L26)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> ```
>  ws.on(messages.outgoing.streamingInMessageDone, ({ sendMessageId }) => {
> ```
Line 19: "events.removeAllListeners();" So the events are not triggered many times.
</blockquote></details>

My mistake that's events not ws, adding a fix


<!-- Sent from Reviewable.io -->

2021-06-22 15:16 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 81 of 82 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 26 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McnyoWs-WnT43UOXVzF:-McoHrYl36T0S4G5i9j-:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L26)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

My mistake that's events not ws, adding a fix
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-22 15:32 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 81 of 82 files reviewed, 4 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 40 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McoKeLx4UN3tYeLErct:-McoKeLy8Om3NpS-d23O:bxbkupt) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L40)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         if (flowName) {
>             hkubeApi.sendMessage(message, flowName);
>         }
>         else if (sendMessage) {
>             sendMessage(message);
>         }
>         else {
>             hkubeApi.sendMessage(message);
>         }
> ```
</details>


There is no meaning for checking the flowName.

It's like writing:

```
if (sendMessage) {
       sendMessage(message);
}
else {
       hkubeApi.sendMessage(message, flowName);
 }
```
___
*[core/algorithm-debug/lib/index.js, line 53 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McoJldL1sSOdMjy0ZCI:-McoJldL1sSOdMjy0ZCJ:b-n755yq) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L53)):*
> ```
>     if (options.kind === pipelineKind.Stream) {
>         if (options.stateType !== stateType.Stateless) {
> ```

I think it's can be more cleaner.

```
const isStateful = options.kind === pipelineKind.Stream && options.stateType !== stateType.Stateless;
if (isStateful) {
 }
```
___
*[core/algorithm-debug/lib/index.js, line 63 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McoLClmBD32fdoA5jhm:-McoLClmBD32fdoA5jhn:bb3gfss) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L63)):*
> ```
> this._prevMsgReject = rej;
> ```
is this used?


<!-- Sent from Reviewable.io -->

2021-06-23 06:59 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 80 of 82 files reviewed, 4 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 40 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McoKeLx4UN3tYeLErct:-McrE-JA-KWWnUuAvKXl:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L40)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         if (flowName) {
>             hkubeApi.sendMessage(message, flowName);
>         }
>         else if (sendMessage) {
>             sendMessage(message);
>         }
>         else {
>             hkubeApi.sendMessage(message);
>         }
> ```

There is no meaning for checking the flowName.

It's like writing:

```
if (sendMessage) {
       sendMessage(message);
}
else {
       hkubeApi.sendMessage(message, flowName);
 }
```
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 53 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McoJldL1sSOdMjy0ZCI:-McrEGzWDeAsddSB82dD:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L53)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     if (options.kind === pipelineKind.Stream) {
>         if (options.stateType !== stateType.Stateless) {
> ```

I think it's can be more cleaner.

```
const isStateful = options.kind === pipelineKind.Stream && options.stateType !== stateType.Stateless;
if (isStateful) {
 }
```
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 63 at r15](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McoLClmBD32fdoA5jhm:-McredeuAnP0VuCXRnjT:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bb627176baf596f2c56233ba4f19c638dd2e9237/core/algorithm-debug/lib/index.js#L63)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> this._prevMsgReject = rej;
> ```
is this used?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-23 11:49 UTC, NassiHarel requested changes
> Reviewed 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 18 at r16](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McsgsRN7_P204GcrHMO:-McsgsROErPu6skeqvzJ:b-9okpj8) ([raw file](https://github.com/kube-hpc/hkube/blob/8a92d5f2cf0fbe49bf4364a97eb4d1d410bb4d42/core/algorithm-debug/lib/index.js#L18)):*
> ```
> log.info('in start');
> ```
Add more logs in all the important areas.


<!-- Sent from Reviewable.io -->

2021-06-23 12:03 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1264)* status: 80 of 82 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 18 at r16](https://reviewable.io/reviews/kube-hpc/hkube/1264#-McsgsRN7_P204GcrHMO:-McskJ0s7AXO2FQE_6-X:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8a92d5f2cf0fbe49bf4364a97eb4d1d410bb4d42/core/algorithm-debug/lib/index.js#L18)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> log.info('in start');
> ```
Add more logs in all the important areas.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-24 07:04 UTC, merged