job priority
kube-HPC/hkube pull request #1466
Opened 2021-12-02 14:44 UTC by golanha

2021-12-05 14:19 UTC, golanha commented
/deploy

2021-12-05 15:20 UTC, golanha commented
/deploy

2021-12-06 12:58 UTC, golanha commented
/deploy

2021-12-15 15:03 UTC, golanha commented
/deploy

2021-12-15 17:54 UTC, golanha commented
/deploy

2021-12-15 18:13 UTC, golanha commented
/deploy

2021-12-16 07:54 UTC, golanha commented
/deploy

2021-12-19 09:20 UTC, golanha commented
/deploy

2021-12-19 09:41 UTC, NassiHarel requested changes
> Reviewed 2 of 7 files at r5, 20 of 34 files at r6, 1 of 4 files at r7, 1 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1466)* status: 24 of 101 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/pipeline-driver-queue/config/main/config.base.js, line 13 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrH1ZiE-zKOHxZwonsA:-MrH1ZiE-zKOHxZwonsB:b-g7ly73) ([raw file](https://github.com/kube-hpc/hkube/blob/db62123d4acd9b1db20d6f8fa9a7852d17aef9b6/core/pipeline-driver-queue/config/main/config.base.js#L13)):*
> ```JavaScript
> 
> config.rest = {
>     port: formatter.parseInt(process.env.REST_PORT, 7000),
> ```

this is HKube GC port



_Code quote:_
```JavaScript
formatter.parseInt(process.env.REST_PORT, 7000),
```
___
*[core/pipeline-driver-queue/lib/persistency/data-store.js, line 34 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrH2nggCD55RJurOErB:-MrH2nggCD55RJurOErC:blb758i) ([raw file](https://github.com/kube-hpc/hkube/blob/db62123d4acd9b1db20d6f8fa9a7852d17aef9b6/core/pipeline-driver-queue/lib/persistency/data-store.js#L34)):*
> ```JavaScript
>     }
> 
>     async getPreferredJobs() {
> ```

Where is the part that you store the `preference` in the db?

don't you need to query the `queueRunner.preferredQueue.queue` ?



_Code quote:_
```JavaScript
async getPreferredJobs() {
```
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 38 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrH3Fbk-rAG2wap2Yv1:-MrH3Fbk-rAG2wap2Yv2:b63wxtq) ([raw file](https://github.com/kube-hpc/hkube/blob/db62123d4acd9b1db20d6f8fa9a7852d17aef9b6/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L38)):*
> ```JavaScript
>     }
> 
>     async addPreferredJobs({ jobs, position, query }) {
> ```

Where is the part for pushing to the `queueRunner.preferredQueue.queue` ?


<!-- Sent from Reviewable.io -->

2021-12-19 10:25 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1466)* status: 24 of 101 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/config/main/config.base.js, line 13 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrH1ZiE-zKOHxZwonsA:-MrH8BsJEm0FHTnQvKOM:bagndxc) ([raw file](https://github.com/kube-hpc/hkube/blob/db62123d4acd9b1db20d6f8fa9a7852d17aef9b6/core/pipeline-driver-queue/config/main/config.base.js#L13)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

this is HKube GC port
</blockquote></details>

Changed to 7100.
___
*[core/pipeline-driver-queue/lib/persistency/data-store.js, line 34 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrH2nggCD55RJurOErB:-MrH8YQjA6btU1WBQa_L:bh280x4) ([raw file](https://github.com/kube-hpc/hkube/blob/db62123d4acd9b1db20d6f8fa9a7852d17aef9b6/core/pipeline-driver-queue/lib/persistency/data-store.js#L34)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Where is the part that you store the `preference` in the db?

don't you need to query the `queueRunner.preferredQueue.queue` ?


</blockquote></details>

you are right its not used, its from a previous implementation.  I removed it.



_Code quote:_
```JavaScript
 async getPreferredJobs(
```
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 38 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrH3Fbk-rAG2wap2Yv1:-MrH8wE0E02tSQFOwVYQ:bhx45qe) ([raw file](https://github.com/kube-hpc/hkube/blob/db62123d4acd9b1db20d6f8fa9a7852d17aef9b6/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L38)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Where is the part for pushing to the `queueRunner.preferredQueue.queue` ?
</blockquote></details>

Line 68:
                queueRunner.preferredQueue.queue.splice(index, 0, dequeued[0]);

I don't use the enqueue() function because I don't want the INSERT event to be invoked and rearrange the queue order. 



_Code quote:_
```JavaScript
 async addPreferredJobs
```


<!-- Sent from Reviewable.io -->

2021-12-19 10:27 UTC, golanha commented
/deploy

2021-12-19 10:47 UTC, yehiyam requested changes
> Reviewed 2 of 71 files at r1, 61 of 69 files at r3, 1 of 7 files at r5, 6 of 34 files at r6, 1 of 4 files at r7, 4 of 5 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1466)* status: all files reviewed, 6 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/openapi-spec/swagger/paths/preferred/preferred.yaml, line 61 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrHEpKUAKroUKkf9_dj:-MrHEpKUAKroUKkf9_dk:b-rgnevt) ([raw file](https://github.com/kube-hpc/hkube/blob/213461c160384e91fc718c1b1fb03054334e34c0/core/openapi-spec/swagger/paths/preferred/preferred.yaml#L61)):*
> ```YAML
>   summary: Remover from preferred
>   description: Remover from preferred
>   requestBody:
> ```

I don't think DELETE with body is something that is standart
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 38 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrHGufFD2z66RfzUieT:-MrHGufFD2z66RfzUieU:bdpbose) ([raw file](https://github.com/kube-hpc/hkube/blob/213461c160384e91fc718c1b1fb03054334e34c0/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L38)):*
> ```JavaScript
>     }
> 
>     async addPreferredJobs({ jobs, position, query }) {
> ```

Why is this method async? I can't find any await
If it is really async, then you risk getting conflicts because finding the index and inserting to the queue is not an atomic operation
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 42 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrHG4S30HQbq46R_QEA:-MrHG4S30HQbq46R_QEB:b-o7ctj2) ([raw file](https://github.com/kube-hpc/hkube/blob/213461c160384e91fc718c1b1fb03054334e34c0/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L42)):*
> ```JavaScript
>         const { tag, pipeline, jobId } = query || {};
>         let index;
>         if (position === 'before') {
> ```

use consts for the position values
Maybe even put these in `@hkube/consts` so it can be used in other services (like api-server)


<!-- Sent from Reviewable.io -->

2021-12-19 13:04 UTC, golanha commented
/deploy

2021-12-19 14:23 UTC, golanha commented
/deploy

2021-12-19 14:39 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1466)* status: 85 of 101 files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/openapi-spec/swagger/paths/preferred/preferred.yaml, line 61 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrHEpKUAKroUKkf9_dj:-MrI7UyC7ceMg4kzqShv:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/213461c160384e91fc718c1b1fb03054334e34c0/core/openapi-spec/swagger/paths/preferred/preferred.yaml#L61)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I don't think DELETE with body is something that is standart
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 38 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrHGufFD2z66RfzUieT:-MrHPBdI8RLJtSo_q1pC:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/213461c160384e91fc718c1b1fb03054334e34c0/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L38)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Why is this method async? I can't find any await
If it is really async, then you risk getting conflicts because finding the index and inserting to the queue is not an atomic operation
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 42 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MrHG4S30HQbq46R_QEA:-MrI7W9H47UJLdtqrQpH:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/213461c160384e91fc718c1b1fb03054334e34c0/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L42)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

use consts for the position values
Maybe even put these in `@hkube/consts` so it can be used in other services (like api-server)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-20 07:00 UTC, golanha commented
/deploy

2021-12-20 07:35 UTC, golanha commented
/deploy

2021-12-20 14:26 UTC, NassiHarel commented on core/pipeline-driver-queue/lib/service/preferred-jobs.js
> +    async deletePreferredJobs(jobIds) {
no async

2021-12-20 14:26 UTC, NassiHarel commented on core/pipeline-driver-queue/lib/service/preferred-jobs.js
> +        if (position === queuePosition.BEFORE) {
This code is a little cumbersome.
Try to split to functions and add some comments

2021-12-20 14:26 UTC, NassiHarel commented on core/pipeline-driver-queue/lib/validation/preference.js
> +            if ((tag && jobId) || (tag && pipeline) || (pipeline && jobId)) {
what if we will add two more variables? 
```
if ((tag && jobId) || (tag && pipeline) || (pipeline && jobId)
|| (pipeline && jobId)|| (pipeline && jobId)|| (pipeline && jobId)
|| (pipeline && jobId)|| (pipeline && jobId)|| (pipeline && jobId)|| (pipeline && jobId)
) {
```

2021-12-21 11:52 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1466)* status: 80 of 103 files reviewed, 9 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 10 at r14](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MqyN-goT6PYFXfGJgji-r14-10:-MrNtgJ63cXyixfUYDk1:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/293771a17de49eb47eb81b5d35ee3c20da4a3172/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L10)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

no async
</blockquote></details>

Done.



_Code quote:_
```JavaScript
 async deletePreferredJobs
```
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 44 at r14](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MqyN-goT6PYFXfGJgji-r14-44:-MrNti6-B0KjKmuD6TUR:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/293771a17de49eb47eb81b5d35ee3c20da4a3172/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L44)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This code is a little cumbersome.
Try to split to functions and add some comments
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/validation/preference.js, line 20 at r14](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MqyN-goT6PYFXfGJgjm-r14-20:-MrR2iFq6YP8qwdsDg6n:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/293771a17de49eb47eb81b5d35ee3c20da4a3172/core/pipeline-driver-queue/lib/validation/preference.js#L20)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

what if we will add two more variables? 
```
if ((tag && jobId) || (tag && pipeline) || (pipeline && jobId)
|| (pipeline && jobId)|| (pipeline && jobId)|| (pipeline && jobId)
|| (pipeline && jobId)|| (pipeline && jobId)|| (pipeline && jobId)|| (pipeline && jobId)
) {
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-21 12:29 UTC, NassiHarel reviewed
> Reviewed 3 of 14 files at r10, 5 of 6 files at r13, 2 of 2 files at r14, 5 of 10 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1466)* status: 94 of 103 files reviewed, 3 unresolved discussions (waiting on @yehiyam)



<!-- Sent from Reviewable.io -->

2021-12-22 09:41 UTC, NassiHarel commented on core/pipeline-driver-queue/api/rest-api/routes/preferred.js
> +    router.get('/', async (req, res) => {
this is not async

2021-12-22 09:41 UTC, NassiHarel commented on core/pipeline-driver-queue/api/rest-api/routes/preferred.js
> +    router.post('/', async (req, res) => {
this is not async

2021-12-22 09:41 UTC, NassiHarel commented on core/pipeline-driver-queue/api/rest-api/routes/preferred.js
> +    router.post('/', async (req, res) => {
This is not a best practice, it is confusing...
The user can set the same jobs ids in `addedJobs` and `removedJobs`...
I think you need to add `router.delete` with a body.

2021-12-22 09:41 UTC, NassiHarel commented on core/pipeline-driver-queue/config/main/config.base.js
> +config.swagger = {
Why you need this?

2021-12-22 09:41 UTC, NassiHarel commented on core/pipeline-driver-queue/lib/validation/preference.js
> +        if ((position === 'first' || position === 'last')) {
```
if ((position === 'first' || position === 'last') && query) {
```

2021-12-22 09:41 UTC, NassiHarel commented on core/pipeline-driver-queue/lib/validation/preference.js
> +            }
You can say
```
 if (numberOfFields === 0) {
      throw new InvalidDataError('Query must contain one of jobId ,tag ,pipelineName');
}
```

2021-12-22 09:41 UTC, NassiHarel commented on core/pipeline-driver-queue/package.json
> +    "performance-now": "^2.1.0",
Do you need `performance-now`?

2021-12-23 07:09 UTC, golanha reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1466)* status: 87 of 104 files reviewed, 9 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/package.json, line 32 at r17](https://reviewable.io/reviews/kube-hpc/hkube/1466#-Mq9fiWTfzpWS4ri48fP-r17-32:-MrXR2Nc--gtFciVor1L:b-kkp36a) ([raw file](https://github.com/kube-hpc/hkube/blob/9c22ec915526dc3bba2e2521c4456138a5c0ac2d/core/pipeline-driver-queue/package.json#L32)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Do you need `performance-now`?
</blockquote></details>

I didn't add it. It is currently  used in scoreing.js
___
*[core/pipeline-driver-queue/config/main/config.base.js, line 18 at r17](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MqyN-goT6PYFXfGJgj_-r17-18:-MrXS3mqDnjiGfC4ushP:b-i5ci1x) ([raw file](https://github.com/kube-hpc/hkube/blob/9c22ec915526dc3bba2e2521c4456138a5c0ac2d/core/pipeline-driver-queue/config/main/config.base.js#L18)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Why you need this?
</blockquote></details>

You are right, I didn't use it.
___
*[core/pipeline-driver-queue/lib/validation/preference.js, line 13 at r17](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MqyN-goT6PYFXfGJgjm-r17-13:-MrXTEY1Dc3VYbnPFhaj:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9c22ec915526dc3bba2e2521c4456138a5c0ac2d/core/pipeline-driver-queue/lib/validation/preference.js#L13)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

```
if ((position === 'first' || position === 'last') && query) {
```
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/validation/preference.js, line 26 at r17](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MqyN-goT6PYFXfGJgjm-r17-26:-MrXSOVG-mqTz3GfWjDV:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9c22ec915526dc3bba2e2521c4456138a5c0ac2d/core/pipeline-driver-queue/lib/validation/preference.js#L26)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

You can say
```
 if (numberOfFields === 0) {
      throw new InvalidDataError('Query must contain one of jobId ,tag ,pipelineName');
}
```
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/api/rest-api/routes/preferred.js, line 7 at r17](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MqyN-goT6PYFXfGJgjX-r17-7:-MrXRvoy6o-yATQc802X:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9c22ec915526dc3bba2e2521c4456138a5c0ac2d/core/pipeline-driver-queue/api/rest-api/routes/preferred.js#L7)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

this is not async
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/api/rest-api/routes/preferred.js, line 11 at r17](https://reviewable.io/reviews/kube-hpc/hkube/1466#-MqyN-goT6PYFXfGJgjX-r17-11:-Mra6q1d0anIzTMxFMA-:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9c22ec915526dc3bba2e2521c4456138a5c0ac2d/core/pipeline-driver-queue/api/rest-api/routes/preferred.js#L11)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This is not a best practice, it is confusing...
The user can set the same jobs ids in `addedJobs` and `removedJobs`...
I think you need to add `router.delete` with a body.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-23 11:19 UTC, golanha commented
/deploy

2021-12-23 13:25 UTC, NassiHarel approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1466#-:-MrbSwlhC99rm7kandfr:bnfp4nl)* status: 87 of 104 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)



<!-- Sent from Reviewable.io -->

2021-12-26 08:33 UTC, golanha commented
/deploy

2021-12-26 09:42 UTC, golanha commented
/deploy

2021-12-27 07:07 UTC, merged