streaming metrics for prometheus
kube-HPC/hkube pull request #1736
Opened 2023-06-06 11:06 UTC by RonShvarz

Added queueSize and throughtput for edges
kube-HPC/hkube#1628

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kube-HPC/hkube/1736)

2023-06-06 11:11 UTC, RonShvarz commented
/deploy

2023-06-06 11:47 UTC, RonShvarz commented
/deploy

2023-06-06 12:00 UTC, RonShvarz commented
/deploy

2023-06-06 13:07 UTC, RonShvarz commented
/deploy test

2023-06-07 07:59 UTC, RonShvarz commented
/deploy

2023-06-07 08:07 UTC, RonShvarz commented
/deploy test

2023-06-07 12:00 UTC, RonShvarz commented
/deploy

2023-06-07 12:43 UTC, RonShvarz commented
/deploy

2023-06-07 12:56 UTC, RonShvarz commented
/deploy

2023-06-08 04:47 UTC, golanha requested changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1736)* status: all files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

___
*[`core/pipeline-driver/lib/metrics/pipeline-metrics.js` line 71 at r8](https://reviewable.io/reviews/kube-HPC/hkube/1736#-NXODoZT2fP6mcY1GhNK:-NXODoZT2fP6mcY1GhNL:b-lekipm) ([raw file](https://github.com/kube-HPC/hkube/blob/3d6b9b3ac86cd59aa1c7a5d376f61580c55209ff/core/pipeline-driver/lib/metrics/pipeline-metrics.js#L71)):*
> ```JavaScript
>     }
> 
>     setStreamingGaugeValueByMetric(options, metricName) {
> ```

setStreamingEdgGaugeMetric



_Code quote:_
```JavaScript
setStreamingGaugeValueByMetric
```
___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 692 at r8](https://reviewable.io/reviews/kube-HPC/hkube/1736#-NXOCawW6QGFE46X2fNv:-NXOCawW6QGFE46X2fNw:b-cf6hyx) ([raw file](https://github.com/kube-HPC/hkube/blob/3d6b9b3ac86cd59aa1c7a5d376f61580c55209ff/core/pipeline-driver/lib/tasks/task-runner.js#L692)):*
> ```JavaScript
>     }
> 
>     _setAllStreamingGaugeMetrics(task, metric) {
> ```

_setStreamingEdgeMetric



_Code quote:_
```JavaScript
_setAllStreamingGaugeMetrics
```


<!-- Sent from Reviewable.io -->

2023-06-08 05:29 UTC, RonShvarz reviewed
Wanted to leave the opprotunity to implements other metrics on edge, which are not gauges, but i can also change it in the future. implemented the changes

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1736#-:-NXOTWyfCMNV0MgDp9MV:b1b86nj)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[`core/pipeline-driver/lib/metrics/pipeline-metrics.js` line 71 at r8](https://reviewable.io/reviews/kube-HPC/hkube/1736#-NXODoZT2fP6mcY1GhNK:-NXOTLMS9m42M0RNA8_p:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/3d6b9b3ac86cd59aa1c7a5d376f61580c55209ff/core/pipeline-driver/lib/metrics/pipeline-metrics.js#L71)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

setStreamingEdgGaugeMetric
</blockquote></details>

Done.
___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 692 at r8](https://reviewable.io/reviews/kube-HPC/hkube/1736#-NXOCawW6QGFE46X2fNv:-NXOTVjI62Z_D6nNsb9C:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/3d6b9b3ac86cd59aa1c7a5d376f61580c55209ff/core/pipeline-driver/lib/tasks/task-runner.js#L692)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

_setStreamingEdgeMetric
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-08 05:35 UTC, golanha approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1736)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)



<!-- Sent from Reviewable.io -->

2023-06-08 05:36 UTC, RonShvarz commented
/deploy

2023-06-08 05:54 UTC, merged