Bug wrapper algorunner out of memory
kube-HPC/hkube pull request #1978
Opened 2024-08-08 13:12 UTC by Adir111

This PR is fixing the bug in the following issue: kube-HPC/hkube#1975
Now, the worker is receiving a new message from the wrapper:  `alive`
And this way the worker knows the wrapper is still up.
The message will be displayed in the log every 30 worker checks (5 minutes).
Also, the method `_printThrottle(topic, message)` has been refactored.

2024-08-11 04:34 UTC, golanha requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1978)* status: all files reviewed, 1 unresolved discussion (waiting on @Adir111)

___
*[`core/worker/lib/worker.js` line 38 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1978#-O3zgCmX7WmN-7NlXnud:-O3zgCmX7WmN-7NlXnue:b-an0b1h) ([raw file](https://github.com/kube-HPC/hkube/blob/d438f1ad95a6d1551ebab0df14827823bf31244f/core/worker/lib/worker.js#L38)):*
> ```JavaScript
>     _initWrapperSettings({
>         isRunning = false,
>         timeoutDuration = 10000
> ```

timeoutduration value should come from config. Allowing to change it by environment variable.



_Code quote:_
```JavaScript
 timeoutDuration = 10000
```


<!-- Sent from Reviewable.io -->

2024-08-14 07:18 UTC, Adir111 reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1978)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`core/worker/lib/worker.js` line 38 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1978#-O3zgCmX7WmN-7NlXnud:-O4Ej9fS7gMBzgmBUXFb:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/d438f1ad95a6d1551ebab0df14827823bf31244f/core/worker/lib/worker.js#L38)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

timeoutduration value should come from config. Allowing to change it by environment variable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-14 11:04 UTC, golanha submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)



<!-- Sent from Reviewable.io -->

2024-08-21 07:34 UTC, golanha approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)



<!-- Sent from Reviewable.io -->

2024-08-21 08:06 UTC, merged