Datasource
kube-HPC/hkube pull request #996
Opened 2020-10-26 11:18 UTC by reggev

2020-10-26 14:58 UTC, NassiHarel requested changes
> Reviewed 3 of 4 files at r1, 30 of 30 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 16 unresolved discussions (waiting on @reggev)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 12 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_2vYHCnPEfgkEXtX-:-MK_2vYHCnPEfgkEXtX0:by66v3l) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/routes/v1/datasource.js#L12)):*
> ```
> const errorsMiddleware
> ```
put this middleware in the folder `api-server/api/rest-api/middlewares`
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 32 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_MnC_E91Wr1AyDbNc:-MK_MnC_E91Wr1AyDbNd:b16o0jo) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/routes/v1/datasource.js#L32)):*
> ```
> const routes = () => {
> ```
The delete dataSource is not reflected in Swagger-UI
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 41 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_B3nD10o4o1ApXZjh:-MK_B3nD10o4o1ApXZji:ba990iz) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/routes/v1/datasource.js#L41)):*
> ```
>  const { name } = req.body;
> ```
This not work through Swagger-UI
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 46 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_2FSvBhVaiUwIzQJz:-MK_2FSvBhVaiUwIzQK-:b-1mny2v) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/routes/v1/datasource.js#L46)):*
> ```
> return res.status(201).json(response);
> ```

look for example at route: /store/pipelines
we do: `res.status(HttpStatus.CREATED).json(response);`
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 56 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_LDDs9ZXv69VtBmEU:-MK_LDDtDoc7NmMi6E6i:b-lhjtca) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/routes/v1/datasource.js#L56)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>                 dataSource: {
>                     ...rest,
>                     href: `datasource/${id}`,
>                     files: files.map(extractFileMeta(id))
>                 }
> ```
</details>

No need to wrap the dataSource with dataSource
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 65 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_MQaI70Rxh-Cz9C5R:-MK_MQaI70Rxh-Cz9C5S:b-ewqhwv) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/routes/v1/datasource.js#L65)):*
> ```
> uploadFile(id, req.file);
> ```

No validation for req.file in PUT method
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 89 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_M0M31Kd18XPXAroM:-MK_M0M31Kd18XPXAroN:byzgv76) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/routes/v1/datasource.js#L89)):*
> ```
> throw new Error
> ```
use middleware for that.
don't throw regular error..... 
___
*[core/api-server/api/rest-api/swagger/definitions/dataSource.yaml, line 3 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_Bqb83biDl53wihHm:-MK_Bqb83biDl53wihHn:b8bejlp) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/swagger/definitions/dataSource.yaml#L3)):*
> ```
> href
> ```
I don't like the `href` prop, maybe `path/link'?
___
*[core/api-server/config/main/config.base.js, line 64 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_CrRQBDZkwjURZ5z8:-MK_CrRQBDZkwjURZ5z9:b-qo6xa8) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/config/main/config.base.js#L64)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         ...(process.env.MONGODB_SERVICE_USER_NAME && process.env.MONGODB_SERVICE_PASSWORD ? {
>             auth: {
>                 user: process.env.MONGODB_SERVICE_USER_NAME,
>                 password: process.env.MONGODB_SERVICE_PASSWORD,
>             },
>         } : {}),
> ```
</details>


I think we need to change this.... :-(

Maybe just:
```
 mongo: {
        auth: {
            user: process.env.MONGODB_SERVICE_USER_NAME,
            password: process.env.MONGODB_SERVICE_PASSWORD,
        },
        host: process.env.MONGODB_SERVICE_HOST || 'localhost',
        port: formatter.parseInt(process.env.MONGODB_SERVICE_PORT, 27017),
        dbName: process.env.MONGODB_SERVICE_NAME || 'hkube',
        useUnifiedTopology: true,
    }

and in the client:

       const { host, port, auth, dbName, ...rest } = config;
        let auth;
        if (config.auth.user && config.auth.password) {
            auth = config.auth;
        }
        const connectionString = `mongodb://${host}:${port}/`;
        this.client = new MongoClient(connectionString, { ...rest, auth });

```
___
*[core/api-server/lib/service/dataSource.js, line 29 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_GlIT-pcZTHQEcDK2:-MK_GlIT-pcZTHQEcDK3:bxegaxp) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/lib/service/dataSource.js#L29)):*
> ```
>         if (!file) {
>             throw new InvalidDataError('no file was submitted');
>         }
> ```
Move this to the validator and also add validation for file ext
___
*[core/api-server/lib/service/dataSource.js, line 51 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_P0lE5deEzSqJ6ic6:-MK_P0lE5deEzSqJ6ic7:b-dp3nkw) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/lib/service/dataSource.js#L51)):*
> ```
> const dataSource 
> ```
Don't return Mongo object
___
*[core/api-server/lib/service/execution.js, line 95 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_PB8v3_lZ7tkq2EK0:-MK_PB8v3_lZ7tkq2EK1:b-7uzmoa) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/lib/service/execution.js#L95)):*
> ```
> storagePrefix: ''
> ```
add the new prefix
___
*[core/api-server/lib/stream/index.js, line 3 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_PFcG65FBLtMhRvAS:-MK_PFcG65FBLtMhRvAT:b-oinhfx) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/lib/stream/index.js#L3)):*
> ```JavaScript
> const { ResourceNotFoundError, InvalidDataError } = require('../errors');
> const NOT_FOUND_CODES = ['ENOENT', 'EISDIR'];
> ```

Great!
gently apply also to /api/storage
___
*[core/api-server/tests/dataSource.test.js, line 54 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_OVmu-JBBq2m5TZ-r:-MK_OVmu-JBBq2m5TZ-s:b-celnyc) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/tests/dataSource.test.js#L54)):*
> ```
> describe.only
> ```
Only :-)
___
*[core/api-server/tests/dataSource.test.js, line 54 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_OaGCDDhRJALKrEIG:-MK_OaGCDDhRJALKrEIH:b-a3i964) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/tests/dataSource.test.js#L54)):*
> ```
> Datasource
> ```
Tests failed if storage is s3
___
*[core/api-server/tests/dataSource.test.js, line 71 at r3](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_PeunAciQt91638yi:-MK_PeunAciQt91638yj:b-3mklvw) ([raw file](https://github.com/kube-hpc/hkube/blob/565562c9a7449641006b2f38d12c13d380517267/core/api [...]

2020-10-26 15:18 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 17 unresolved discussions (waiting on @reggev)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 40 at r3](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_T1GO4pzvogI6ospq:-MK_T1GO4pzvogI6ospr:bbz07f5) ([raw file](https://github.com/kube-hpc/hkube/blob/565562c9a7449641006b2f38d12c13d380517267/core/api-server/api/rest-api/routes/v1/datasource.js#L40)):*
> ```
> async (req, res)
> ```
Where is next after req, res?


<!-- Sent from Reviewable.io -->

2020-10-27 08:14 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 20 unresolved discussions (waiting on @reggev)

___
*[core/api-server/bootstrap.js, line 20 at r3](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKd2bTD76r-tj7pi0pI:-MKd2bTD76r-tj7pi0pJ:b-ht9obv) ([raw file](https://github.com/kube-hpc/hkube/blob/565562c9a7449641006b2f38d12c13d380517267/core/api-server/bootstrap.js#L20)):*
> ```
>  require('./lib/db')
> ```
if you move this to the top of the list, you will able to do
```
const { db } = require('../db');
```

and no more 
```
const db = dbConnection.connection;
```
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 86 at r3](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKd5a_v08N58Q8HGtRU:-MKd5a_v08N58Q8HGtRV:bj4hsw4) ([raw file](https://github.com/kube-hpc/hkube/blob/565562c9a7449641006b2f38d12c13d380517267/core/api-server/api/rest-api/routes/v1/datasource.js#L86)):*
> ```
>             if (error.code === 'ENOENT') {
>                 throw new ResourceNotFoundError('dataSource/file', `${id}/${fileName}`);
>             }
> ```
Search the function `handleStorageError`
___
*[core/api-server/lib/service/dataSource.js, line 54 at r3](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKd5zeB2jg2bY4uXsKy:-MKd5zeB2jg2bY4uXsKz:b4ge6rr) ([raw file](https://github.com/kube-hpc/hkube/blob/565562c9a7449641006b2f38d12c13d380517267/core/api-server/lib/service/dataSource.js#L54)):*
> ```
> return { ...dataSource, files: files.map(file => file.path) };
> ```

We already have a convention for returning files list.
After running the dataSource tests, try to call.

http://localhost:3000/api/v1/storage/keys/local-hkube-datasource/<datasourceID>


<!-- Sent from Reviewable.io -->

2020-10-28 09:47 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 19 of 35 files reviewed, 22 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/service/dataSource.js, line 25 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKiYZJ_-JqiWpqbZB_b:-MKiYZJ_-JqiWpqbZB_c:b-phkqpq) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L25)):*
> ```
>  async uploadFile(dataSourceId, file) {
> ```
You also need to delete the file in `uploads/datasource`
___
*[core/api-server/tests/dataSource.test.js, line 367 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKi_FkP61fK93cXhX3B:-MKi_FkP61fK93cXhX3C:b-1nd783) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/tests/dataSource.test.js#L367)):*
> ```
> const { response } = await createDataSource({ body: { name } });
> ```

For now, this works fine, because it a simple key-value.
but... if dataSource was more than just a `name` it wasn't working at all.
```
const { response } = await createDataSource({ body: { name, options: { use: true } } });
```

It will not work.. dataSource is not expandable.
If dataSource will have more props you will have to change your API.


<!-- Sent from Reviewable.io -->

2020-10-28 09:48 UTC, reggevam reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 19 of 35 files reviewed, 22 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 12 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_2vYHCnPEfgkEXtX-:-MKd5U9B1jo2AGsyIjTc:bsygml9) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/routes/v1/datasource.js#L12)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const errorsMiddleware
> ```
put this middleware in the folder `api-server/api/rest-api/middlewares`
</blockquote></details>

This is not a generic middleware, it is very specific to this route and should be used only here.
I don't think it should be located with the other middlewares 


<!-- Sent from Reviewable.io -->

2020-10-28 10:03 UTC, NassiHarel requested changes
> Reviewed 1 of 30 files at r2, 5 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 23 of 35 files reviewed, 22 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/consts/regex.js, line 8 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKieNCv2B9HBJ_IHbsO:-MKieNCv2B9HBJ_IHbsP:b-90wf73) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/consts/regex.js#L8)):*
> ```
> BINARY_FILE_NAME: /^[\w,\s-]+\.[A-Za-z]+$/i,
> ```

Why a user needs a file with ext?


<!-- Sent from Reviewable.io -->

2020-10-28 10:09 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 23 of 35 files reviewed, 23 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 71 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKifFFwCjzNayZULMbF:-MKifFFwCjzNayZULMbG:bwqm2i2) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/api/rest-api/routes/v1/datasource.js#L71)):*
> ```
>  const deletedId = await dataSource.delete(id);
> ```
This is not true, you call inside to `Promise.all` which calls two functions.
So it cannot return `deletedId`.
It returns:
```
{
  "deleted": [
    "5f99413900ce311c61b65237",
    null
  ]
}
```


<!-- Sent from Reviewable.io -->

2020-10-28 10:17 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 23 of 35 files reviewed, 24 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/consts/regex.js, line 8 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKihR6C2pyf7deYaYC4:-MKihR6C2pyf7deYaYC5:btf14sb) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/consts/regex.js#L8)):*
> ```
> BINARY_FILE_NAME: /^[\w,\s-]+\.[A-Za-z]+$/i,
> ```

This is also preventing from user to upload `.7zip`


<!-- Sent from Reviewable.io -->

2020-10-28 10:42 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 23 of 35 files reviewed, 25 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/service/dataSource.js, line 19 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKimexHCuQS22bLhA8P:-MKimexHCuQS22bLhA8Q:brt4171) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L19)):*
> ```
> async updateDataSource(dataSourceId, file) {
> ```

basically, I can pass any `dataSourceId` that I want, and this method will upload as usual...
need validation...


<!-- Sent from Reviewable.io -->

2020-10-28 11:13 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 23 of 35 files reviewed, 26 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/service/dataSource.js, line 28 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKitXXE7CreMZysWStl:-MKitXXE7CreMZysWStm:b-ijx83v) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L28)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         const createdPath = await storage.hkubeDataSource.putStream({
>             dataSource: dataSourceId,
>             data: fse.createReadStream(file.path),
>             fileName: file.originalname
>         });
> ```
</details>


If you save the files in the format of:
"datasource/5f9950cc0413d80b310dfda0/<file>"

The user needs to define the pipeline like this:
```
 "nodeName": "node",
 "algorithmName": "alg",
 "input": [
          "@dataSource.5f9950cc0413d80b310dfda0/<file>"
]
```

The user needs to write something like:
```
"nodeName": "node",
 "algorithmName": "alg",
 "input": [
          "@dataSource.images/<file>"
]
```


<!-- Sent from Reviewable.io -->

2020-10-28 14:15 UTC, NassiHarel requested changes
> Reviewed 4 of 17 files at r4, 1 of 4 files at r5, 4 of 5 files at r6, 2 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 27 of 34 files reviewed, 20 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 72 at r7](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKjYeGpCXsvEFQALUHO:-MKjYeGpCXsvEFQALUHP:bjf0zjv) ([raw file](https://github.com/kube-hpc/hkube/blob/ad6db6717168fad7fdae289302814bcdcb0f413f/core/api-server/api/rest-api/routes/v1/datasource.js#L72)):*
> ```
> res.status(HttpStatus.OK).
> ```
I think it's the default status, no need...
___
*[core/api-server/api/rest-api/swagger/definitions/dataSourceFile.yaml, line 3 at r7](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKjYoUr0T1zGVCycdN-:-MKjYoUr0T1zGVCycdN0:b-9o9crk) ([raw file](https://github.com/kube-hpc/hkube/blob/ad6db6717168fad7fdae289302814bcdcb0f413f/core/api-server/api/rest-api/swagger/definitions/dataSourceFile.yaml#L3)):*
> ```
> # required: true
> ```
Don't leave comments


<!-- Sent from Reviewable.io -->

2020-10-28 14:15 UTC, NassiHarel reviewed
> Reviewed 1 of 17 files at r4, 1 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 29 of 34 files reviewed, 20 unresolved discussions (waiting on @NassiHarel and @reggev)



<!-- Sent from Reviewable.io -->

2020-10-28 16:28 UTC, NassiHarel reviewed
> Reviewed 2 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 26 of 35 files reviewed, 18 unresolved discussions (waiting on @NassiHarel and @reggev)



<!-- Sent from Reviewable.io -->

2020-10-28 16:34 UTC, NassiHarel requested changes
> Reviewed 1 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 27 of 35 files reviewed, 20 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/service/dataSource.js, line 56 at r8](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKk2c6W3QCov73YYIjh:-MKk2c6XAKEbcmnu4L6G:b-n0awux) ([raw file](https://github.com/kube-hpc/hkube/blob/36347754f8df9a456826563ff9449dbe4372e52c/core/api-server/lib/service/dataSource.js#L56)):*
> ```
> .toString()
> ```
no need now for toString()
___
*[core/api-server/lib/service/dataSource.js, line 56 at r8](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKk2lE36ziN8oK5XrgP:-MKk2lE4EzUmphswk7OF:bk8bg0m) ([raw file](https://github.com/kube-hpc/hkube/blob/36347754f8df9a456826563ff9449dbe4372e52c/core/api-server/lib/service/dataSource.js#L56)):*
> ```
> hkubeDataSource.list
> ```
list with stats


<!-- Sent from Reviewable.io -->

2020-10-28 16:37 UTC, NassiHarel reviewed
> Reviewed 1 of 17 files at r4, 1 of 5 files at r6, 1 of 5 files at r7, 4 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 34 of 35 files reviewed, 10 unresolved discussions (waiting on @NassiHarel and @reggev)



<!-- Sent from Reviewable.io -->

2020-10-29 07:37 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 31 of 35 files reviewed, 11 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/service/dataSource.js, line 36 at r9](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKnFdpC-Qz2ZW4GDvhI:-MKnFdpD1gf7dqauA0sJ:ba0q7cq) ([raw file](https://github.com/kube-hpc/hkube/blob/26d893722b1491c8b4b5635e9977d6a5e2b94f73/core/api-server/lib/service/dataSource.js#L36)):*
> ```
>         finally {
>             await fse.remove(file.path);
>         }
> ```
I think it's still not so good, the validation that happens before can throw before this method.
It must be at the route level.


<!-- Sent from Reviewable.io -->

2020-10-29 07:44 UTC, NassiHarel reviewed
> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 11 unresolved discussions (waiting on @reggev)



<!-- Sent from Reviewable.io -->

2020-10-29 13:29 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 27 of 35 files reviewed, 10 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 72 at r7](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKjYeGpCXsvEFQALUHO:-MKkDeok6ydPmGMl91by:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ad6db6717168fad7fdae289302814bcdcb0f413f/core/api-server/api/rest-api/routes/v1/datasource.js#L72)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> res.status(HttpStatus.OK).
> ```
I think it's the default status, no need...
</blockquote></details>

Done.
___
*[core/api-server/api/rest-api/swagger/definitions/dataSource.yaml, line 3 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_Bqb83biDl53wihHm:-MKkDha_1W9aehB6KSit:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/api/rest-api/swagger/definitions/dataSource.yaml#L3)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> href
> ```
I don't like the `href` prop, maybe `path/link'?
</blockquote></details>

Done.
___
*[core/api-server/lib/service/dataSource.js, line 54 at r3](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKd5zeB2jg2bY4uXsKy:-MKkK7dWBhgA74zEhWaD:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/565562c9a7449641006b2f38d12c13d380517267/core/api-server/lib/service/dataSource.js#L54)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> return { ...dataSource, files: files.map(file => file.path) };
> ```

We already have a convention for returning files list.
After running the dataSource tests, try to call.

http://localhost:3000/api/v1/storage/keys/local-hkube-datasource/<datasourceID>

</blockquote></details>

Done.
___
*[core/api-server/lib/service/dataSource.js, line 19 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKimexHCuQS22bLhA8P:-MKkLkvq6GYTepIkV7VG:b-dhedy7) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L19)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> async updateDataSource(dataSourceId, file) {
> ```

basically, I can pass any `dataSourceId` that I want, and this method will upload as usual...
need validation...
</blockquote></details>

This should be a POST request not a PUT, i'll update it accordingly
___
*[core/api-server/lib/service/dataSource.js, line 25 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKiYZJ_-JqiWpqbZB_b:-MKkDr-s9pV1WsauRcvg:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L25)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  async uploadFile(dataSourceId, file) {
> ```
You also need to delete the file in `uploads/datasource`
</blockquote></details>

Done.
___
*[core/api-server/lib/service/dataSource.js, line 28 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKitXXE7CreMZysWStl:-MKoXmNqCaEG6zTlpjn8:bh1pflb) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L28)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         const createdPath = await storage.hkubeDataSource.putStream({
>             dataSource: dataSourceId,
>             data: fse.createReadStream(file.path),
>             fileName: file.originalname
>         });
> ```

If you save the files in the format of:
"datasource/5f9950cc0413d80b310dfda0/<file>"

The user needs to define the pipeline like this:
```
 "nodeName": "node",
 "algorithmName": "alg",
 "input": [
          "@dataSource.5f9950cc0413d80b310dfda0/<file>"
]
```

The user needs to write something like:
```
"nodeName": "node",
 "algorithmName": "alg",
 "input": [
          "@dataSource.images/<file>"
]
```



</blockquote></details>

I converted all the actions to based on the name instead of the ID, it is unique (using unique index under the hood) and should be easier to use, updated the db and the storage to match 
___
*[core/api-server/lib/service/dataSource.js, line 56 at r8](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKk2c6W3QCov73YYIjh:-MKkOcZ_Dx0acDOUXG3k:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/36347754f8df9a456826563ff9449dbe4372e52c/core/api-server/lib/service/dataSource.js#L56)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> .toString()
> ```
no need now for toString()
</blockquote></details>

Done.
___
*[core/api-server/lib/service/dataSource.js, line 56 at r8](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKk2lE36ziN8oK5XrgP:-MKkOb_i0hmq_1VcDUfx:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/36347754f8df9a456826563ff9449dbe4372e52c/core/api-server/lib/service/dataSource.js#L56)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> hkubeDataSource.list
> ```
list with stats
</blockquote></details>

Done.
___
*[core/api-server/lib/service/dataSource.js, line 36 at r9](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKnFdpC-Qz2ZW4GDvhI:-MKoXhKz1RMjJe5onoiI:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/26d893722b1491c8b4b5635e9977d6a5e2b94f73/core/api-server/lib/service/dataSource.js#L36)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         finally {
>             await fse.remove(file.path);
>         }
> ```
I think it's still not so good, the validation that happens before can throw before this method.
It must be at the route level.

</blockquote></details>

Done.
___
*[core/api-server/tests/dataSource.test.js, line 367 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKi_FkP61fK93cXhX3B:-MKkKF6i68jd-QvSNsB7:b202lw9) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/tests/dataSource.test.js#L367)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const { response } = await createDataSource({ body: { name } });
> ```

For now, this works fine, because it a simple key-value.
but... if dataSource was more than just a `name` it wasn't working at all.
```
const { response } = await createDataSource({ body: { name, options: { use: true } } });
```

It will not work.. dataSource is not expandable.
If dataSource will have more props you will have to change your API.


</blockquote></details>

The issue with nested fields is caused because of multipart form data being key/value only, for now we don't need nested fields, we'll solve this in the future if needed 


<!-- Sent from Reviewable.io -->

2020-10-29 13:29 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 27 of 35 files reviewed, 10 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/service/dataSource.js, line 28 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKitXXE7CreMZysWStl:-MKoY8rm3jjsMpHKScbe:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L28)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

I converted all the actions to based on the name instead of the ID, it is unique (using unique index under the hood) and should be easier to use, updated the db and the storage to match 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 13:41 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 27 of 35 files reviewed, 10 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[core/api-server/lib/service/dataSource.js, line 19 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKimexHCuQS22bLhA8P:-MKo_kLT3ZIcl5sBy2Gq:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L19)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

This should be a POST request not a PUT, i'll update it accordingly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 15:17 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 26 of 35 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/config/main/config.base.js, line 64 at r2](https://reviewable.io/reviews/kube-hpc/hkube/996#-MK_CrRQBDZkwjURZ5z8:-MKotXz25oA32vKUbFhD:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2ce78483c1ac9610e9f3e75f69cbc03f18c1d307/core/api-server/config/main/config.base.js#L64)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         ...(process.env.MONGODB_SERVICE_USER_NAME && process.env.MONGODB_SERVICE_PASSWORD ? {
>             auth: {
>                 user: process.env.MONGODB_SERVICE_USER_NAME,
>                 password: process.env.MONGODB_SERVICE_PASSWORD,
>             },
>         } : {}),
> ```

I think we need to change this.... :-(

Maybe just:
```
 mongo: {
        auth: {
            user: process.env.MONGODB_SERVICE_USER_NAME,
            password: process.env.MONGODB_SERVICE_PASSWORD,
        },
        host: process.env.MONGODB_SERVICE_HOST || 'localhost',
        port: formatter.parseInt(process.env.MONGODB_SERVICE_PORT, 27017),
        dbName: process.env.MONGODB_SERVICE_NAME || 'hkube',
        useUnifiedTopology: true,
    }

and in the client:

       const { host, port, auth, dbName, ...rest } = config;
        let auth;
        if (config.auth.user && config.auth.password) {
            auth = config.auth;
        }
        const connectionString = `mongodb://${host}:${port}/`;
        this.client = new MongoClient(connectionString, { ...rest, auth });

```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-29 15:24 UTC, reggevam reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 26 of 35 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/lib/service/dataSource.js, line 19 at r4](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKimexHCuQS22bLhA8P:-MKk6ot613NebMoFuXUq:b-gkc7gg) ([raw file](https://github.com/kube-hpc/hkube/blob/aab11e5e3e2a9246ca1859bef456f070a6d6eb8b/core/api-server/lib/service/dataSource.js#L19)):*
> I think it's the default status, no need...


<!-- Sent from Reviewable.io -->

2020-10-29 15:24 UTC, reggevam reviewed
> Reviewed 1 of 4 files at r1, 10 of 30 files at r2, 6 of 17 files at r4, 1 of 4 files at r5, 2 of 5 files at r6, 1 of 5 files at r7, 5 of 7 files at r8, 1 of 4 files at r9, 9 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)



<!-- Sent from Reviewable.io -->

2020-10-29 15:37 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 4 unresolved discussions (waiting on @reggev)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 37 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKoyWUQ2mi04BkYvuIy:-MKoyWUQ2mi04BkYvuIz:bio1934) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/api/rest-api/routes/v1/datasource.js#L37)):*
> ```
> req.file && await fse.remove(req.file.path);
> ```
duplicate code detected, move to function
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 43 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKozVvX0UHHnbqV2o6C:-MKozVvX0UHHnbqV2o6D:b83ecmn) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/api/rest-api/routes/v1/datasource.js#L43)):*
> ```
> .route('/:name')
> ```
RESTFul API should have POST, PUT, GET, DELETE.
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 58 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKoyccdD71oOfDDBlFC:-MKoycce0NhmLv2xzbR_:b-1hxosu) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/api/rest-api/routes/v1/datasource.js#L58)):*
> ```
> await dataSource.fetchDataSource(name);
> ```
This will fetch data source but also all related files... inefficient...
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 61 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKp-1S2Avqqt3jtiGhr:-MKp-1S2Avqqt3jtiGhs:b-4g43ob) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/api/rest-api/routes/v1/datasource.js#L61)):*
> ```
> res.status(HttpStatus.CREATED).
> ```
redundant


<!-- Sent from Reviewable.io -->

2020-11-01 06:39 UTC, NassiHarel requested changes
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 4 unresolved discussions (waiting on @reggev)

___
*[core/api-server/lib/service/dataSource.js, line 36 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-ML1WdGM70pwHcYyTvwF:-ML1WdGM70pwHcYyTvwG:bd2sdy) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/lib/service/dataSource.js#L36)):*
> ```
> async createDataSource(name, file) {
> ```
It's better to pass an object instead of arguments, for all functions in this service.


<!-- Sent from Reviewable.io -->

2020-11-04 10:34 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 28 of 40 files reviewed, 4 unresolved discussions (waiting on @NassiHarel and @reggevam)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 37 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKoyWUQ2mi04BkYvuIy:-MLHoZxX1KkpYTIStwQy:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/api/rest-api/routes/v1/datasource.js#L37)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> req.file && await fse.remove(req.file.path);
> ```
duplicate code detected, move to function
</blockquote></details>

Done.
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 43 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKozVvX0UHHnbqV2o6C:-MLHnBml5kS7-6SKxKEP:b-73q0v1) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/api/rest-api/routes/v1/datasource.js#L43)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> .route('/:name')
> ```
RESTFul API should have POST, PUT, GET, DELETE.
</blockquote></details>

For now the data source does not contain any fields other than its name and id. 
I'll add patch(edit) and put(upsert) when we'll have more fields to actually update.
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 58 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKoyccdD71oOfDDBlFC:-MLHjoxgEz4vLA4hxzhP:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/api/rest-api/routes/v1/datasource.js#L58)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> await dataSource.fetchDataSource(name);
> ```
This will fetch data source but also all related files... inefficient...
</blockquote></details>

Done.
___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 61 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-MKp-1S2Avqqt3jtiGhr:-MLCOKA65HWJab9F4Q3C:bjkc40o) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/api/rest-api/routes/v1/datasource.js#L61)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> res.status(HttpStatus.CREATED).
> ```
redundant
</blockquote></details>

Not redundant, status 200 is the default, this case should be 201
___
*[core/api-server/lib/service/dataSource.js, line 36 at r10](https://reviewable.io/reviews/kube-hpc/hkube/996#-ML1WdGM70pwHcYyTvwF:-ML2CkdfB9pJLyKrdmiC:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ffcde085e2e76273246af4f41169ffd795c8999a/core/api-server/lib/service/dataSource.js#L36)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> async createDataSource(name, file) {
> ```
It's better to pass an object instead of arguments, for all functions in this service.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-04 14:18 UTC, NassiHarel requested changes
> Reviewed 2 of 8 files at r12, 9 of 9 files at r13, 1 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 4 unresolved discussions (waiting on @reggev)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 62 at r13](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLIQRho6Fo2Yz71zNJj:-MLIQRho6Fo2Yz71zNJk:b-nh05v6) ([raw file](https://github.com/kube-hpc/hkube/blob/33baaf91997f24ab7dd65bd3f050a8edd16fe609/core/api-server/api/rest-api/routes/v1/datasource.js#L62)):*
> ```
>             // validates the data source exists
>             await dataSource.fetchDataSourceMetaData({ name });
> ```

This should be inside `updateDataSource`
___
*[core/api-server/lib/service/dataSource.js, line 92 at r13](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLIQwqP2MjTI6UXKVn9:-MLIQwqP2MjTI6UXKVnA:b4svw37) ([raw file](https://github.com/kube-hpc/hkube/blob/33baaf91997f24ab7dd65bd3f050a8edd16fe609/core/api-server/lib/service/dataSource.js#L92)):*
> ```
>  dataSourceId
> ```
At some point, it called `dataSource`, some point `dataSourceId`, and at another point, it called just `name`. 
___
*[core/api-server/lib/validation/dataSource.js, line 3 at r13](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLISz5H3GIw4IlAf6Cp:-MLISz5H3GIw4IlAf6Cq:b-ej2i5z) ([raw file](https://github.com/kube-hpc/hkube/blob/33baaf91997f24ab7dd65bd3f050a8edd16fe609/core/api-server/lib/validation/dataSource.js#L3)):*
> ```
> /** @typedef {import('express')} Express */
> ```
express?
___
*[core/api-server/tests/exec- datasource.js, line 17 at r15](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLIaG1V5aMA1fwxgzqS:-MLIaG1WADmUFyYzbZgZ:b-mxcqns) ([raw file](https://github.com/kube-hpc/hkube/blob/5d053c387081d0b0fdf4344c5cb66845e8d79522/core/api-server/tests/exec- datasource.js#L17)):*
> ```
> it('should throw invalid reserved name dataSource', async () => {
> ```
Need to add tests when it does succeed


<!-- Sent from Reviewable.io -->

2020-11-05 12:40 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 36 of 39 files reviewed, 4 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/api/rest-api/routes/v1/datasource.js, line 62 at r13](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLIQRho6Fo2Yz71zNJj:-MLIs6sm7sbWKALE9l03:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/33baaf91997f24ab7dd65bd3f050a8edd16fe609/core/api-server/api/rest-api/routes/v1/datasource.js#L62)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>             // validates the data source exists
>             await dataSource.fetchDataSourceMetaData({ name });
> ```

This should be inside `updateDataSource`
</blockquote></details>

Done.
___
*[core/api-server/lib/service/dataSource.js, line 92 at r13](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLIQwqP2MjTI6UXKVn9:-MLIs8KK89BeBpQWvJoe:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/33baaf91997f24ab7dd65bd3f050a8edd16fe609/core/api-server/lib/service/dataSource.js#L92)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  dataSourceId
> ```
At some point, it called `dataSource`, some point `dataSourceId`, and at another point, it called just `name`. 
</blockquote></details>

Done.
___
*[core/api-server/lib/validation/dataSource.js, line 3 at r13](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLISz5H3GIw4IlAf6Cp:-MLIn4AO5IkX9orx1tRf:b5j0o6s) ([raw file](https://github.com/kube-hpc/hkube/blob/33baaf91997f24ab7dd65bd3f050a8edd16fe609/core/api-server/lib/validation/dataSource.js#L3)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> /** @typedef {import('express')} Express */
> ```
express?
</blockquote></details>

this is used for the Express.Multer.File definition
___
*[core/api-server/tests/exec- datasource.js, line 17 at r15](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLIaG1V5aMA1fwxgzqS:-MLNQ-3x4nApK7gGL94s:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5d053c387081d0b0fdf4344c5cb66845e8d79522/core/api-server/tests/exec- datasource.js#L17)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> it('should throw invalid reserved name dataSource', async () => {
> ```
Need to add tests when it does succeed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 14:28 UTC, NassiHarel requested changes
> Reviewed 4 of 4 files at r16, 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel, @reggev, and @yehiyam)

___
*[core/api-server/lib/service/dataSource.js, line 52 at r16](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLNmguA0eBaMO3AT1P1:-MLNmguA0eBaMO3AT1P2:bz3t91v) ([raw file](https://github.com/kube-hpc/hkube/blob/e21912838b2011a5752e07494efcc9c84baa0d42/core/api-server/lib/service/dataSource.js#L52)):*
> ```
> db.dataSources.create(name);
> ```
make this function accept an object, add also new property `created` (epoch)
___
*[core/api-server/tests/exec- datasource.js, line 50 at r16](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLNnUnm3dsqPIfeRcJL:-MLNnUnm3dsqPIfeRcJM:b5x40kx) ([raw file](https://github.com/kube-hpc/hkube/blob/e21912838b2011a5752e07494efcc9c84baa0d42/core/api-server/tests/exec- datasource.js#L50)):*
> ```
> it('should succeed and return job id', async () => {
> ```
almost, I added the test...


<!-- Sent from Reviewable.io -->

2020-11-16 08:32 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 21 of 39 files reviewed, 3 unresolved discussions (waiting on @NassiHarel, @reggevam, and @yehiyam)

___
*[core/api-server/lib/service/dataSource.js, line 52 at r16](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLNmguA0eBaMO3AT1P1:-MMFAYXlEK50LkjfUrsj:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/e21912838b2011a5752e07494efcc9c84baa0d42/core/api-server/lib/service/dataSource.js#L52)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> db.dataSources.create(name);
> ```
make this function accept an object, add also new property `created` (epoch)
</blockquote></details>

Done.
___
*[core/api-server/lib/validation/dataSource.js, line 3 at r13](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLISz5H3GIw4IlAf6Cp:-MMFA_c1-8E7iF_0qz1f:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/33baaf91997f24ab7dd65bd3f050a8edd16fe609/core/api-server/lib/validation/dataSource.js#L3)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

this is used for the Express.Multer.File definition
</blockquote></details>

Done.
___
*[core/api-server/tests/exec- datasource.js, line 50 at r16](https://reviewable.io/reviews/kube-hpc/hkube/996#-MLNnUnm3dsqPIfeRcJL:-MMFAdUYBmEmyxlWUets:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/e21912838b2011a5752e07494efcc9c84baa0d42/core/api-server/tests/exec- datasource.js#L50)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> it('should succeed and return job id', async () => {
> ```
almost, I added the test...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-30 10:09 UTC, NassiHarel reviewed
> Reviewed 3 of 20 files at r20, 28 of 113 files at r21, 74 of 90 files at r22.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 82 of 118 files reviewed, 14 unresolved discussions (waiting on @NassiHarel, @reggev, and @yehiyam)

___
*[core/datasources-service/bootstrap.js, line 30 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn0vI-75Q0awr7upLk:-MPn0vI-75Q0awr7upLl:b-slc7h) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/bootstrap.js#L30)):*
> ```
> true
> ```
this should set to false, only the api-server creates buckets/fs
___
*[core/datasources-service/package.json, line 6 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn16icDlOtFmJgj-cF:-MPn16icDlOtFmJgj-cG:bidybnk) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/package.json#L6)):*
> ```
>  "dependencies": {
> ```
need to clean unused packages
___
*[core/datasources-service/README.md, line 2 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn1CpSEaf3kmmiF0wH:-MPn1CpT1-uIJxrTHVNk:bpkb3wd) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/README.md#L2)):*
> ```
> api-server
> ```
need to chnahe
___
*[core/datasources-service/config/main/config.base.js, line 13 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn1m9g-ycxXhIETyEF:-MPn1m9g-ycxXhIETyEG:b-tle5bf) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/config/main/config.base.js#L13)):*
> ```
> config.maxStorageFetchKeys
> ```
need to clean all copy-paste configs
___
*[core/datasources-service/dockerfile/Dockerfile, line 3 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2-vz5EBrSQl5_6pT:-MPn2-vz5EBrSQl5_6pU:bnff5k8) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/dockerfile/Dockerfile#L3)):*
> ```Dockerfile
> ARG BASE_PRIVATE_REGISTRY=""
> FROM ${BASE_PRIVATE_REGISTRY}hkube/base-node:v1.2.0
> LABEL maintainer="reggev.am@gmail.com"
> ```

install git
RUN apt update && apt install -y git gettext-base && rm -rf /var/lib/apt/lists/*

install dvc
RUN wget \
       https://dvc.org/deb/dvc.list \
       -O /etc/apt/sources.list.d/dvc.list
RUN apt update
RUN apt install dvc
___
*[core/datasources-service/lib/service/dataSource.js, line 38 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2NDy0Ril4I8OOil1:-MPn2NDy0Ril4I8OOil2:bziipcd) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/service/dataSource.js#L38)):*
> ```JavaScript
>         this.config = config;
>         db = dbConnection.connection;
>         fse.ensureDirSync(this.config.directories.temporaryGitRepositories);
> ```

why not async?
___
*[core/datasources-service/lib/service/jobs-consumer.js, line 53 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2aBXDP7ehFeT3hDg:-MPn2aBXDP7ehFeT3hDh:b-sgjdxk) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/service/jobs-consumer.js#L53)):*
> ```
> error: `could not find the datasource ${dataSource.name}`

> ```
How do you know the error is 'could not find'?

Why the error is unused? (in the entire class)
Maybe add log.error?
___
*[core/datasources-service/lib/utils/dvc.js, line 3 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn46e68BRjFtw4Sz5b:-MPn462mBBPY3acKNFc1:b-w5ae87) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/dvc.js#L3)):*
> ```JavaScript
> const storage = require('@hkube/storage-manager');
> 
> const { HKUBE_DATASOURCE } = storage.STORAGE_PREFIX.STORAGE_PREFIX;
> ```

Firts:
You need to get the real prefix:
`const prefix = storage.hkubeDataSource.prefix;`

Second:
I think it is better to do:
```
const configs = {
    's3': getS3Config
    'fs': getFSConfig
}
```

because in your code there is:
```
 storage === 'fs'
                ? dvcConfig.getFSConfig
                : dvcConfig.getS3Config({
```
And this is only for two storage types, if you add more types, more `if's`
___
*[core/datasources-service/lib/utils/Repository.js, line 48 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn5RZA1Sa0FDbH8HT4:-MPn5RZA1Sa0FDbH8HT5:bv1c5yx) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/Repository.js#L48)):*
> ```
>  const generateDvcConfig =
> ```
This should be inited only once, at startup.
___
*[core/datasources-service/lib/utils/Repository.js, line 53 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn5YnKACQiFRzLw20q:-MPn5YnKACQiFRzLw20r:b-pvzb9r) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/Repository.js#L53)):*
> ```
> bucketName:
> ```
You dont have this in getS3Config
___
*[core/datasources-service/lib/utils/Repository.js, line 198 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn6NBAAXj40p49A4e0:-MPn6NBAAXj40p49A4e1:b-1tumbx) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/Repository.js#L198)):*
> ```JavaScript
>         return null;
>     }
> ```

Why not creating dvc client?
```
dvc = new dvcClient();
dvc.init();
dvc.add();
```


<!-- Sent from Reviewable.io -->

2020-12-30 12:58 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 82 of 118 files reviewed, 14 unresolved discussions (waiting on @NassiHarel, @reggev, and @yehiyam)

___
*[core/datasources-service/bootstrap.js, line 30 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn0vI-75Q0awr7upLk:-MPngGfCBzH1txzDLHv7:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/bootstrap.js#L30)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> true
> ```
this should set to false, only the api-server creates buckets/fs
</blockquote></details>

Done.
___
*[core/datasources-service/README.md, line 2 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn1CpSEaf3kmmiF0wH:-MPngUrs0lNHT6N3eROW:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/README.md#L2)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> api-server
> ```
need to chnahe
</blockquote></details>

Done.
___
*[core/datasources-service/lib/service/dataSource.js, line 38 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2NDy0Ril4I8OOil1:-MPnZVsyCE3Ua54p229w:bo2ck97) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/service/dataSource.js#L38)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

why not async?
</blockquote></details>

It happens once on bootstrapping and should not start serving until this is ready
___
*[core/datasources-service/lib/utils/dvc.js, line 3 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn46e68BRjFtw4Sz5b:-MPnex21BvaC0T-aGvzr:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/dvc.js#L3)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Firts:
You need to get the real prefix:
`const prefix = storage.hkubeDataSource.prefix;`

Second:
I think it is better to do:
```
const configs = {
    's3': getS3Config
    'fs': getFSConfig
}
```

because in your code there is:
```
 storage === 'fs'
                ? dvcConfig.getFSConfig
                : dvcConfig.getS3Config({
```
And this is only for two storage types, if you add more types, more `if's`

</blockquote></details>

Done.
___
*[core/datasources-service/lib/utils/Repository.js, line 48 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn5RZA1Sa0FDbH8HT4:-MPnf-VbBL3JODwYZYOp:b-dwcfx4) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/Repository.js#L48)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  const generateDvcConfig =
> ```
This should be inited only once, at startup.
</blockquote></details>

it should happen before push or pull and be saved into a .local config, this config contains keys and should not be pushed to the git reposity .local configs are gitignored by default (according to dvc's docs)
___
*[core/datasources-service/lib/utils/Repository.js, line 53 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn5YnKACQiFRzLw20q:-MPnfrUS688u8xZijsr6:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/Repository.js#L53)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> bucketName:
> ```
You dont have this in getS3Config
</blockquote></details>

Done.
___
*[core/datasources-service/lib/utils/Repository.js, line 198 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn6NBAAXj40p49A4e0:-MPnftdC6pe409dvjbN8:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/Repository.js#L198)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Why not creating dvc client?
```
dvc = new dvcClient();
dvc.init();
dvc.add();
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-30 13:14 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 82 of 118 files reviewed, 14 unresolved discussions (waiting on @NassiHarel, @reggev, and @yehiyam)

___
*[core/datasources-service/lib/service/jobs-consumer.js, line 53 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2aBXDP7ehFeT3hDg:-MPnmHiO2oC9l4jfnXbf:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/service/jobs-consumer.js#L53)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> error: `could not find the datasource ${dataSource.name}`

> ```
How do you know the error is 'could not find'?

Why the error is unused? (in the entire class)
Maybe add log.error?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-11 14:23 UTC, NassiHarel reviewed
> Reviewed 1 of 17 files at r4, 1 of 2 files at r15, 1 of 20 files at r20, 23 of 113 files at r21, 6 of 90 files at r22, 107 of 108 files at r23.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: all files reviewed, 5 unresolved discussions (waiting on @reggev and @yehiyam)

___
*[core/datasources-service/lib/service/dataSource.js, line 38 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2NDy0Ril4I8OOil1:-MQlmr755sKXiyJlE7je:b5dcrdg) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/service/dataSource.js#L38)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

It happens once on bootstrapping and should not start serving until this is ready
</blockquote></details>

This is wrong, you are starting serving because in the bootstrap the `app-server` is first, 
just make it async and control the order of bootstraping
___
*[core/datasources-service/lib/service/dataSource.js, line 319 at r23](https://reviewable.io/reviews/kube-hpc/hkube/996#-MQlotCb1Se85IkiJbQ0:-MQlotCb1Se85IkiJbQ1:btyede7) ([raw file](https://github.com/kube-hpc/hkube/blob/e0f64b72190ca6f7b79906419830c9bccaba7de5/core/datasources-service/lib/service/dataSource.js#L319)):*
> ```JavaScript
>     async create({ name, files: _files }) {
>         validator.dataSources.create({ name, files: _files });
>         const createdDataSource = await this.db.dataSources.create({ name });
> ```

Add `time created`
___
*[core/datasources-service/lib/utils/Repository.js, line 48 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn5RZA1Sa0FDbH8HT4:-MQlnNdi57ca5hRvNrLc:b-wz9e91) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/utils/Repository.js#L48)):*
>  before push or pull and be saved into a .local config, this config contains keys and should not be pushed to the git

This is wrong, this can be set only once at startup, the storage is not changing during runtime


<!-- Sent from Reviewable.io -->

2021-01-13 14:53 UTC, reggev reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 145 of 162 files reviewed, 5 unresolved discussions (waiting on @NassiHarel, @reggev, and @yehiyam)

___
*[core/datasources-service/dockerfile/Dockerfile, line 3 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2-vz5EBrSQl5_6pT:-MQwCAmk32sMQZKHVKZi:b-wol4m4) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/dockerfile/Dockerfile#L3)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

install git
RUN apt update && apt install -y git gettext-base && rm -rf /var/lib/apt/lists/*

install dvc
RUN wget \
       https://dvc.org/deb/dvc.list \
       -O /etc/apt/sources.list.d/dvc.list
RUN apt update
RUN apt install dvc
</blockquote></details>

the whole file was re-written matching the new format
___
*[core/datasources-service/lib/service/dataSource.js, line 38 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2NDy0Ril4I8OOil1:-MQwCTsuEeRjSAjpV6NL:bb7f2mf) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/service/dataSource.js#L38)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This is wrong, you are starting serving because in the bootstrap the `app-server` is first, 
just make it async and control the order of bootstraping
</blockquote></details>

done
___
*[core/datasources-service/lib/service/dataSource.js, line 319 at r23](https://reviewable.io/reviews/kube-hpc/hkube/996#-MQlotCb1Se85IkiJbQ0:-MQwCpsv32ZZ4p-kD3T6:b96bl06) ([raw file](https://github.com/kube-hpc/hkube/blob/e0f64b72190ca6f7b79906419830c9bccaba7de5/core/datasources-service/lib/service/dataSource.js#L319)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Add `time created`
</blockquote></details>

the time created is included in the id of the dataSource (mongodb's _id)


<!-- Sent from Reviewable.io -->

2021-01-13 15:55 UTC, NassiHarel reviewed
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/996)* status: 141 of 163 files reviewed, 4 unresolved discussions (waiting on @NassiHarel, @reggev, and @yehiyam)

___
*[core/datasources-service/lib/service/dataSource.js, line 38 at r22](https://reviewable.io/reviews/kube-hpc/hkube/996#-MPn2NDy0Ril4I8OOil1:-MQwSJLd56eu-0-9p8zG:b-yhahrg) ([raw file](https://github.com/kube-hpc/hkube/blob/21fee905fbc2657ee345a5563fe789aa66e448e8/core/datasources-service/lib/service/dataSource.js#L38)):*
> ```
> ensureDirSync
> ```
You are still using this `ensureDirSync`
___
*[core/datasources-service/lib/service/dataSource.js, line 319 at r23](https://reviewable.io/reviews/kube-hpc/hkube/996#-MQlotCb1Se85IkiJbQ0:-MQwR8UOErfCRyUMmEup:b-i2x3j2) ([raw file](https://github.com/kube-hpc/hkube/blob/e0f64b72190ca6f7b79906419830c9bccaba7de5/core/datasources-service/lib/service/dataSource.js#L319)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

the time created is included in the id of the dataSource (mongodb's _id)
</blockquote></details>


Yes, I know, but what is it helps if you don't return it to the API/UI?

And you will have to do some iteration over the collection to convert this ID to use the `getTimestamp()`

And what if you will want time modified?


<!-- Sent from Reviewable.io -->

2021-01-18 12:07 UTC, reggev commented
/deploy

2021-01-18 12:48 UTC, yehiyam commented
/deploy

2021-01-19 11:48 UTC, reggev commented
/deploy dev1

2021-01-21 14:34 UTC, yehiyam commented
/deploy

2021-01-21 15:34 UTC, yehiyam commented
/deploy

2021-01-21 16:20 UTC, yehiyam commented
/deploy

2021-01-24 07:44 UTC, merged